<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 3 Análisis exploratorio de datos (EDA) | Notas de métodos estadísticos</title>
  <meta name="description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 3 Análisis exploratorio de datos (EDA) | Notas de métodos estadísticos" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 3 Análisis exploratorio de datos (EDA) | Notas de métodos estadísticos" />
  
  <meta name="twitter:description" content="This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook." />
  

<meta name="author" content="Carlos de Oro Aguado" />


<meta name="date" content="2025-07-27" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="literature.html"/>
<link rel="next" href="applications.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/codefolding-lua-1.1/codefolding-lua.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/kePrint-0.0.1/kePrint.js"></script>
<link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
<link href="libs/bsTable-3.3.7/bootstrapTable.min.css" rel="stylesheet" />
<script src="libs/bsTable-3.3.7/bootstrapTable.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Notas de métodos estadísticos</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Asignatura</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introducción</a>
<ul>
<li class="chapter" data-level="1.1" data-path="03-method.html"><a href="#introducci%C3%B3n-a-r-y-rstudio"><i class="fa fa-check"></i><b>1.1</b> Introducción a R y RStudio</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="03-method.html"><a href="#qu%C3%A9-es-r"><i class="fa fa-check"></i><b>1.1.1</b> ¿Qué es R?</a></li>
<li class="chapter" data-level="1.1.2" data-path="03-method.html"><a href="#qu%C3%A9-es-rstudio"><i class="fa fa-check"></i><b>1.1.2</b> ¿Qué es RStudio?</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="03-method.html"><a href="#introducci%C3%B3n-a-git-y-github"><i class="fa fa-check"></i><b>1.2</b> Introducción a Git y GitHub</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="03-method.html"><a href="#qu%C3%A9-es-git"><i class="fa fa-check"></i><b>1.2.1</b> ¿Qué es Git?</a></li>
<li class="chapter" data-level="1.2.2" data-path="03-method.html"><a href="#qu%C3%A9-es-github"><i class="fa fa-check"></i><b>1.2.2</b> ¿Qué es GitHub?</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="03-method.html"><a href="#introducci%C3%B3n-a-tidyverse"><i class="fa fa-check"></i><b>1.3</b> Introducción a Tidyverse</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="03-method.html"><a href="#representaci%C3%B3n-visual-del-ecosistema-tidyverse"><i class="fa fa-check"></i><b>1.3.1</b> Representación visual del ecosistema Tidyverse</a></li>
<li class="chapter" data-level="1.3.2" data-path="intro.html"><a href="intro.html#principales-paquetes-del-tidyverse"><i class="fa fa-check"></i><b>1.3.2</b> Principales paquetes del Tidyverse</a></li>
<li class="chapter" data-level="1.3.3" data-path="03-method.html"><a href="#instalaci%C3%B3n-del-tidyverse-en-r"><i class="fa fa-check"></i><b>1.3.3</b> Instalación del Tidyverse en R</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#pasos-para-publicar-un-libro-bookdown-en-github-pages"><i class="fa fa-check"></i><b>1.4</b> Pasos para publicar un libro <code>bookdown</code> en GitHub Pages</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="03-method.html"><a href="#video-paso-a-paso-de-la-publicaci%C3%B3n-del-libro-en-github-pages"><i class="fa fa-check"></i><b>1.4.1</b> Video paso a paso de la publicación del libro en GitHub Pages</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="literature.html"><a href="literature.html"><i class="fa fa-check"></i><b>2</b> Reglas de curso y diagnostico</a>
<ul>
<li class="chapter" data-level="2.1" data-path="literature.html"><a href="literature.html#reglas-de-las-clases"><i class="fa fa-check"></i><b>2.1</b> Reglas de las clases</a></li>
<li class="chapter" data-level="2.2" data-path="03-method.html"><a href="#pol%C3%ADtica-de-evaluaci%C3%B3n-y-normas-de-integridad-acad%C3%A9mica"><i class="fa fa-check"></i><b>2.2</b> Política de evaluación y normas de integridad académica</a></li>
<li class="chapter" data-level="2.3" data-path="literature.html"><a href="literature.html#fechas-de-taller-y-examenes"><i class="fa fa-check"></i><b>2.3</b> Fechas de taller y examenes</a></li>
<li class="chapter" data-level="2.4" data-path="03-method.html"><a href="#programaci%C3%B3n-del-curso-por-unidad"><i class="fa fa-check"></i><b>2.4</b> Programación del curso por unidad</a></li>
<li class="chapter" data-level="2.5" data-path="literature.html"><a href="literature.html#referencias"><i class="fa fa-check"></i><b>2.5</b> Referencias</a></li>
<li class="chapter" data-level="2.6" data-path="03-method.html"><a href="#terminos-b%C3%A1sicos-de-la-estad%C3%ADstica"><i class="fa fa-check"></i><b>2.6</b> Terminos básicos de la estadística</a></li>
<li class="chapter" data-level="2.7" data-path="03-method.html"><a href="#diagnostico-de-estad%C3%ADstica-b%C3%A1sica"><i class="fa fa-check"></i><b>2.7</b> Diagnostico de estadística básica</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="method.html"><a href="method.html"><i class="fa fa-check"></i><b>3</b> Análisis exploratorio de datos (EDA)</a>
<ul>
<li class="chapter" data-level="3.1" data-path="03-method.html"><a href="#cu%C3%A1ndo-debo-utilizarlo"><i class="fa fa-check"></i><b>3.1</b> ¿Cuándo debo utilizarlo?</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="03-method.html"><a href="#tipos-de-an%C3%A1lisis-exploratorio"><i class="fa fa-check"></i><b>3.1.1</b> Tipos de análisis exploratorio:</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="03-method.html"><a href="#representaci%C3%B3n-de-datos-seg%C3%BAn-su-naturaleza"><i class="fa fa-check"></i><b>3.2</b> Representación de datos según su naturaleza</a></li>
<li class="chapter" data-level="3.3" data-path="03-method.html"><a href="#presentaci%C3%B3n-y-an%C3%A1lisis-de-la-informaci%C3%B3n-en-estudios-descriptivos"><i class="fa fa-check"></i><b>3.3</b> Presentación y análisis de la información en estudios descriptivos</a></li>
<li class="chapter" data-level="3.4" data-path="03-method.html"><a href="#an%C3%A1lisis-explotario-con-variable-respuesta-num%C3%A9rica"><i class="fa fa-check"></i><b>3.4</b> Análisis explotario con variable respuesta numérica</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="method.html"><a href="method.html#contexto-de-los-datos-de-walmart"><i class="fa fa-check"></i><b>3.4.1</b> Contexto de los datos de Walmart</a></li>
<li class="chapter" data-level="3.4.2" data-path="03-method.html"><a href="#extracci%C3%B3n-transformaci%C3%B3n-y-carga-etl"><i class="fa fa-check"></i><b>3.4.2</b> Extracción, transformación y carga (ETL)</a></li>
<li class="chapter" data-level="3.4.3" data-path="03-method.html"><a href="#an%C3%A1lisis-de-la-variable-weekly_sales-target"><i class="fa fa-check"></i><b>3.4.3</b> Análisis de la variable <code>weekly_sales</code> (Target)</a></li>
<li class="chapter" data-level="3.4.4" data-path="03-method.html"><a href="#an%C3%A1lisis-de-las-variables-caracter%C3%ADsticas-independientes"><i class="fa fa-check"></i><b>3.4.4</b> Análisis de las variables características (independientes)</a></li>
<li class="chapter" data-level="3.4.5" data-path="03-method.html"><a href="#an%C3%A1lisis-exploratorio-bivariado"><i class="fa fa-check"></i><b>3.4.5</b> Análisis exploratorio bivariado</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Notas de métodos estadísticos</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="method" class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Capítulo 3</span> Análisis exploratorio de datos (EDA)<a href="method.html#method" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:r-fig"></span>
<img src="images/eda.png" alt="Análisis exploratorio de datos (EDA)" width="30%" />
<p class="caption">
Figura 3.1: Análisis exploratorio de datos (EDA)
</p>
</div>
<p>El <strong>Análisis Exploratorio de Datos</strong> (<em>Exploratory Data Analysis</em>, EDA por sus siglas en inglés) es una etapa fundamental del proceso estadístico que consiste en utilizar <strong>gráficos, visualizaciones y resúmenes numéricos</strong> para examinar un conjunto de datos.</p>
<p>Su propósito principal es <strong>explorar, descubrir patrones, identificar anomalías y formular posibles hipótesis</strong>, sin realizar inferencias estadísticas formales. El EDA busca <strong>comprender la estructura de los datos</strong> y generar ideas, más que confirmar hipótesis previamente establecidas.</p>
<div id="cuándo-debo-utilizarlo" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> ¿Cuándo debo utilizarlo?<a href="#cu%C3%A1ndo-debo-utilizarlo" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El <strong>Análisis Exploratorio de Datos (EDA)</strong> es una herramienta poderosa para examinar, comprender y preparar un conjunto de datos. Aunque el análisis esté orientado a hipótesis específicas, el EDA es útil en etapas previas como la limpieza de datos, la detección de errores, el análisis de subgrupos o simplemente para obtener una mejor comprensión de la estructura y comportamiento de los datos.</p>
<p>Uno de los pasos iniciales más importantes del EDA es la <strong>representación gráfica de los datos</strong>, que permite identificar patrones, tendencias y valores atípicos con mayor claridad.</p>
<div id="tipos-de-análisis-exploratorio" class="section level3 hasAnchor" number="3.1.1">
<h3><span class="header-section-number">3.1.1</span> Tipos de análisis exploratorio:<a href="#tipos-de-an%C3%A1lisis-exploratorio" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li><strong>No gráfico:</strong> Utiliza estadísticas descriptivas para resumir las variables numéricamente.</li>
<li><strong>Gráfico:</strong> Representa visualmente los datos mediante histogramas, diagramas de caja, gráficos de dispersión, entre otros.</li>
<li><strong>Univariado:</strong> Analiza una sola variable a la vez, observando su distribución, tendencia central y dispersión.</li>
<li><strong>Multivariado:</strong> Examina dos o más variables simultáneamente, identificando relaciones o asociaciones entre ellas.</li>
</ul>
<p>Cada una de estas divisiones puede, a su vez, clasificarse según el tipo de variable involucrada: <strong>categórica</strong> o <strong>numérica</strong>.</p>
</div>
</div>
<div id="representación-de-datos-según-su-naturaleza" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Representación de datos según su naturaleza<a href="#representaci%C3%B3n-de-datos-seg%C3%BAn-su-naturaleza" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>La forma en que se representan los datos depende fundamentalmente de su <strong>naturaleza</strong>, es decir, del <strong>tipo de variable</strong> que se está analizando. Esta clasificación influye directamente en la selección de métodos gráficos y estadísticos adecuados para el análisis.</p>
<table>
<caption><span id="tab:tipo">Tabla 3.1: </span>Fechas de cortes y distribución de porcentajes</caption>
<colgroup>
<col width="14%" />
<col width="9%" />
<col width="6%" />
<col width="13%" />
<col width="12%" />
<col width="13%" />
<col width="30%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">Naturaleza.de.la.variable</th>
<th align="left">Escala.de.Medidas</th>
<th align="left">Frecuencias</th>
<th align="left">Medidas.de.Localización</th>
<th align="left">Medidas.de.Dispersión</th>
<th align="left">Medidas.de.Distribución</th>
<th align="left">Gráficos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Cualitativa</td>
<td align="left">Nominal</td>
<td align="left">Sí</td>
<td align="left">Moda</td>
<td align="left">No</td>
<td align="left">No</td>
<td align="left">Sectores, Barras</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left">Ordinal</td>
<td align="left">Sí</td>
<td align="left">Moda</td>
<td align="left">No</td>
<td align="left">No</td>
<td align="left">Sectores, Barras (sin orden)</td>
</tr>
<tr class="odd">
<td align="left">Cuantitativa</td>
<td align="left">Intervalo</td>
<td align="left">Agrupadas</td>
<td align="left">Media, Mediana y Moda</td>
<td align="left">Sí</td>
<td align="left">Sí</td>
<td align="left">Histograma, Tallo y hojas, Cajas y Bigotes, Dispersión</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="left">Razón</td>
<td align="left"></td>
<td align="left"></td>
<td align="left">Sí</td>
<td align="left">Sí</td>
<td align="left"></td>
</tr>
</tbody>
</table>
</div>
<div id="presentación-y-análisis-de-la-información-en-estudios-descriptivos" class="section level2 hasAnchor" number="3.3">
<h2><span class="header-section-number">3.3</span> Presentación y análisis de la información en estudios descriptivos<a href="#presentaci%C3%B3n-y-an%C3%A1lisis-de-la-informaci%C3%B3n-en-estudios-descriptivos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En los estudios descriptivos, la presentación y análisis de la información constituyen fases clave para comprender las características fundamentales de los datos recolectados. El objetivo principal es <strong>resumir y organizar</strong> la información de forma clara y accesible, sin realizar inferencias ni establecer relaciones causales.</p>
<table class="table table-striped table-hover table-condensed table-responsive" style="color: black; width: auto !important; margin-left: auto; margin-right: auto;">
<caption>
<span id="tab:representacion">Tabla 3.2: </span>Relación entre tipo de tabla y tipo de gráfico
</caption>
<thead>
<tr>
<th style="text-align:left;font-weight: bold;color: black !important;background-color: rgba(217, 226, 241, 255) !important;">
Tipo de Tabla
</th>
<th style="text-align:left;font-weight: bold;color: black !important;background-color: rgba(217, 226, 241, 255) !important;">
Tipo de Gráfico
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;color: black !important;background-color: rgba(231, 231, 231, 255) !important;width: 4cm; ">
De Frecuencia (Variable Cualitativa)
</td>
<td style="text-align:left;color: black !important;background-color: rgba(231, 231, 231, 255) !important;width: 6cm; ">
<ul>
<li>Barras simples</li>
<li>Pastel
</td>
</tr>
<tr>
<td style="text-align:left;color: black !important;background-color: white !important;width: 4cm; ">
De Frecuencia (Variable Cuantitativa)
</td>
<td style="text-align:left;color: black !important;background-color: white !important;width: 6cm; ">
<ul>
<li>Histograma
</td>
</tr>
<tr>
<td style="text-align:left;color: black !important;background-color: rgba(242, 242, 242, 255) !important;width: 4cm; ">
De Asociacion (Dos Variables Cualitativas)
</td>
<td style="text-align:left;color: black !important;background-color: rgba(242, 242, 242, 255) !important;width: 6cm; ">
<ul>
<li>Barras compuestas</li>
</ul></li>
</ul></li>
<li>Barras superpuestas
</td>
</tr>
<tr>
<td style="text-align:left;color: black !important;background-color: rgba(242, 242, 242, 255) !important;width: 4cm; ">
De Asociacion (Una Variable Cualitativa y una Cuantitativa Discreta)
</td>
<td style="text-align:left;color: black !important;background-color: rgba(242, 242, 242, 255) !important;width: 6cm; ">
<ul>
<li>Barras:</li>
<li>Compuestas</li>
<li>Superpuestas
</td>
</tr>
<tr>
<td style="text-align:left;color: black !important;background-color: white !important;width: 4cm; ">
De Asociacion (Una Variable Cualitativa y una Cuantitativa Continua)
</td>
<td style="text-align:left;color: black !important;background-color: white !important;width: 6cm; ">
<ul>
<li>Poligono de Frecuencia</li>
</ul></li>
</ul></li>
<li>Box plot (diagrama de cajas y bigotes)
</td>
</tr>
<tr>
<td style="text-align:left;color: black !important;background-color: rgba(231, 231, 231, 255) !important;width: 4cm; ">
De Asociacion (Dos Variables Cuantitativas)
</td>
<td style="text-align:left;color: black !important;background-color: rgba(231, 231, 231, 255) !important;width: 6cm; ">
<ul>
<li>Diagrama de Puntos
</td>
</tr>
</tbody>
</table></li>
</ul></li>
</ul>
</div>
<div id="análisis-explotario-con-variable-respuesta-numérica" class="section level2 hasAnchor" number="3.4">
<h2><span class="header-section-number">3.4</span> Análisis explotario con variable respuesta numérica<a href="#an%C3%A1lisis-explotario-con-variable-respuesta-num%C3%A9rica" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Para el desarrollo de las visualización trabajaremos con datos sobre los almacenes Walmart, que es un cadena de grande almacenes de Ewa.</p>
<div class="figure" style="text-align: center"><span style="display:block;" id="fig:r-fig-2"></span>
<img src="images/walmart.png" alt="Tienda Walmart" width="50%" />
<p class="caption">
Figura 3.2: Tienda Walmart
</p>
</div>
<p>El conjunto de datos completos lo puede encontrar este <a href="https://www.kaggle.com/datasets/yasserh/walmart-dataset/data">link</a>. Trabajaremos un subconjunto de datos contiene las ventas semanales en dolares, cada tienda tiene un número de identificación y un tipo de tienda específico, las ventas estan separadas por ID de departamento. Junto con las ventas hay variables como si fue de vacaciones o no, la temperatura media durante la semana en esa localidad, el tiempo medio del combustible en dolares por litro esa semana y la tasa de desempleo de esa semana.</p>
<div id="contexto-de-los-datos-de-walmart" class="section level3 hasAnchor" number="3.4.1">
<h3><span class="header-section-number">3.4.1</span> Contexto de los datos de Walmart<a href="method.html#contexto-de-los-datos-de-walmart" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Aquí tienes una explicación de las variables en el conjunto de datos de ventas proporcionado:</p>
<ul>
<li><p><strong>Unnamed</strong>: Columna de índice que parece haber sido incluida al guardar el archivo. No es una variable significativa.</p></li>
<li><p><strong>store</strong>: Identificador del número de la tienda.</p></li>
<li><p><strong>type</strong>: Tipo de tienda, representado por una letra (por ejemplo, “A”, “B”, etc.).
n<br />
</p></li>
<li><p><strong>department</strong>: Identificador del número de departamento dentro de la tienda.</p></li>
<li><p><strong>date</strong>: Fecha en la que se registró la venta.</p></li>
<li><p><strong>weekly_sales</strong>: Ventas semanales en USD registradas en esa tienda y departamento específicos (<code>Target</code>).</p></li>
<li><p><strong>is_holiday</strong>: Variable booleana que indica si la fecha corresponde a un día festivo o no. Los valores son “True” o “False”.</p></li>
<li><p><strong>temperature_c</strong>: Temperatura en grados Celsius en la fecha registrada.</p></li>
<li><p><strong>fuel_price_usd_per_l</strong>: Precio del combustible en dólares estadounidenses por litro en la fecha registrada.</p></li>
<li><p><strong>unemployment</strong>: Tasa de desempleo en la fecha registrada.</p></li>
</ul>
<p>Iniciaremos el análisis exploratorio de los datos de Walmart</p>
</div>
<div id="extracción-transformación-y-carga-etl" class="section level3 hasAnchor" number="3.4.2">
<h3><span class="header-section-number">3.4.2</span> Extracción, transformación y carga (ETL)<a href="#extracci%C3%B3n-transformaci%C3%B3n-y-carga-etl" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>Carguemos el conjunto de datos:</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="method.html#cb7-1" tabindex="-1"></a>url <span class="ot">&lt;-</span> <span class="st">&quot;https://raw.githubusercontent.com/cdeoroaguado/Datos/refs/heads/main/datamanip/sales.csv&quot;</span></span>
<span id="cb7-2"><a href="method.html#cb7-2" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(url)</span></code></pre></div>
</details>
<ul>
<li>Verifiquemos que leímos bien los datos viendo el encabezado y la cola de los datos:</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="method.html#cb8-1" tabindex="-1"></a><span class="fu">head</span>(datos,<span class="at">n=</span><span class="dv">5</span>)</span></code></pre></div>
</details>
<pre><code>##   X store type department       date weekly_sales is_holiday temperature_c fuel_price_usd_per_l unemployment
## 1 0     1    A          1 2010-02-05     24924.50      False      5.727778            0.6794508        8.106
## 2 1     1    A          1 2010-03-05     21827.90      False      8.055556            0.6934520        8.106
## 3 2     1    A          1 2010-04-02     57258.43      False     16.816667            0.7182841        7.808
## 4 3     1    A          1 2010-05-07     17413.94      False     22.527778            0.7489281        7.808
## 5 4     1    A          1 2010-06-04     17558.09      False     27.050000            0.7145857        7.808</code></pre>
<p>Las dimensiones, los nombres de las columnas y la estructura de la base de datos se obtienen con los códigos:</p>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="method.html#cb10-1" tabindex="-1"></a><span class="fu">dim</span>(datos)</span></code></pre></div>
</details>
<pre><code>## [1] 10774    10</code></pre>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="method.html#cb12-1" tabindex="-1"></a><span class="fu">colnames</span>(datos)</span></code></pre></div>
</details>
<pre><code>##  [1] &quot;X&quot;                    &quot;store&quot;                &quot;type&quot;                 &quot;department&quot;          
##  [5] &quot;date&quot;                 &quot;weekly_sales&quot;         &quot;is_holiday&quot;           &quot;temperature_c&quot;       
##  [9] &quot;fuel_price_usd_per_l&quot; &quot;unemployment&quot;</code></pre>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="method.html#cb14-1" tabindex="-1"></a><span class="fu">str</span>(datos)</span></code></pre></div>
</details>
<pre><code>## &#39;data.frame&#39;:    10774 obs. of  10 variables:
##  $ X                   : int  0 1 2 3 4 5 6 7 8 9 ...
##  $ store               : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ type                : chr  &quot;A&quot; &quot;A&quot; &quot;A&quot; &quot;A&quot; ...
##  $ department          : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ date                : chr  &quot;2010-02-05&quot; &quot;2010-03-05&quot; &quot;2010-04-02&quot; &quot;2010-05-07&quot; ...
##  $ weekly_sales        : num  24925 21828 57258 17414 17558 ...
##  $ is_holiday          : chr  &quot;False&quot; &quot;False&quot; &quot;False&quot; &quot;False&quot; ...
##  $ temperature_c       : num  5.73 8.06 16.82 22.53 27.05 ...
##  $ fuel_price_usd_per_l: num  0.679 0.693 0.718 0.749 0.715 ...
##  $ unemployment        : num  8.11 8.11 7.81 7.81 7.81 ...</code></pre>
<ul>
<li>Eliminemos la variable <code>X</code> y <code>date</code>, ya que no estan en nuestra investigación:</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="method.html#cb16-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb16-2"><a href="method.html#cb16-2" tabindex="-1"></a></span>
<span id="cb16-3"><a href="method.html#cb16-3" tabindex="-1"></a>datos <span class="sc">%&gt;%</span> </span>
<span id="cb16-4"><a href="method.html#cb16-4" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>X,<span class="sc">-</span>date) <span class="ot">-&gt;</span> df</span></code></pre></div>
</details>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="method.html#cb17-1" tabindex="-1"></a><span class="fu">head</span>(df, <span class="at">n=</span><span class="dv">5</span>)</span></code></pre></div>
</details>
<pre><code>##   store type department weekly_sales is_holiday temperature_c fuel_price_usd_per_l unemployment
## 1     1    A          1     24924.50      False      5.727778            0.6794508        8.106
## 2     1    A          1     21827.90      False      8.055556            0.6934520        8.106
## 3     1    A          1     57258.43      False     16.816667            0.7182841        7.808
## 4     1    A          1     17413.94      False     22.527778            0.7489281        7.808
## 5     1    A          1     17558.09      False     27.050000            0.7145857        7.808</code></pre>
<ul>
<li>Identifiquemos los valores <code>NA</code> por columna:</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="method.html#cb19-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="method.html#cb19-2" tabindex="-1"></a>    <span class="fu">summarise</span>(<span class="fu">across</span>(<span class="fu">everything</span>(), <span class="sc">~</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(.)), <span class="at">.names =</span> <span class="st">&quot;NA_{.col}&quot;</span>))</span></code></pre></div>
</details>
<pre><code>##   NA_store NA_type NA_department NA_weekly_sales NA_is_holiday NA_temperature_c NA_fuel_price_usd_per_l
## 1        0       0             0               0             0                0                       0
##   NA_unemployment
## 1               0</code></pre>
<ul>
<li>Otra forma de hacerlo es:</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="method.html#cb21-1" tabindex="-1"></a><span class="fu">library</span>(Amelia)</span>
<span id="cb21-2"><a href="method.html#cb21-2" tabindex="-1"></a></span>
<span id="cb21-3"><a href="method.html#cb21-3" tabindex="-1"></a><span class="fu">missmap</span>(df)</span></code></pre></div>
</details>
<p><img src="bookdown-demo_files/figure-html/na-amelia-1.png" width="672" /></p>
</div>
<div id="análisis-de-la-variable-weekly_sales-target" class="section level3 hasAnchor" number="3.4.3">
<h3><span class="header-section-number">3.4.3</span> Análisis de la variable <code>weekly_sales</code> (Target)<a href="#an%C3%A1lisis-de-la-variable-weekly_sales-target" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>Consideremos el resumen de la <code>weekly_sales</code>:</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="method.html#cb22-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb22-2"><a href="method.html#cb22-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb22-3"><a href="method.html#cb22-3" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(weekly_sales),</span>
<span id="cb22-4"><a href="method.html#cb22-4" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(weekly_sales),</span>
<span id="cb22-5"><a href="method.html#cb22-5" tabindex="-1"></a>    <span class="at">ds =</span> <span class="fu">sd</span>(weekly_sales),</span>
<span id="cb22-6"><a href="method.html#cb22-6" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(weekly_sales),</span>
<span id="cb22-7"><a href="method.html#cb22-7" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(weekly_sales),</span>
<span id="cb22-8"><a href="method.html#cb22-8" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(weekly_sales),</span>
<span id="cb22-9"><a href="method.html#cb22-9" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(weekly_sales, <span class="fl">0.25</span>),</span>
<span id="cb22-10"><a href="method.html#cb22-10" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(weekly_sales, <span class="fl">0.75</span>),</span>
<span id="cb22-11"><a href="method.html#cb22-11" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(weekly_sales)</span>
<span id="cb22-12"><a href="method.html#cb22-12" tabindex="-1"></a>  )</span></code></pre></div>
</details>
<pre><code>##       n    media       ds  mediana minimo maximo       Q1       Q3      IQR
## 1 10774 23843.95 30220.39 12049.06  -1098 293966 3867.115 32349.85 28482.73</code></pre>
<p>La variable <code>weekly_sales</code> fue analizada a partir de 10.774 observaciones. Se obtuvo un promedio de ventas semanales de aproximadamente <span class="math inline">\(23.843,95\)</span> usd (DS = <span class="math inline">\(30.220,39\)</span> usd), donde El <span class="math inline">\(50\%\)</span> de las ventas semanales se encuentran por debajo de <span class="math inline">\(12.049,06\)</span> usd. El mínimo registrado fue de <span class="math inline">\(-1.098\)</span> usd, lo que indica que en ciertas semanas se presentaron saldos negativos de ventas, posiblemente debido a devoluciones de productos, ajustes contables o cancelaciones, situaciones comunes en grandes cadenas minoristas como Walmart. Por su parte, el máximo alcanzó los <span class="math inline">\(293.966\)</span> usd, lo cual refleja una alta heterogeneidad entre tiendas o departamentos.</p>
<ul>
<li>Veamos un histograma</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="method.html#cb24-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb24-2"><a href="method.html#cb24-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> weekly_sales)) <span class="sc">+</span></span>
<span id="cb24-3"><a href="method.html#cb24-3" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">y =</span> <span class="fu">after_stat</span>(density)), </span>
<span id="cb24-4"><a href="method.html#cb24-4" tabindex="-1"></a>                 <span class="at">binwidth =</span> <span class="dv">5000</span>, </span>
<span id="cb24-5"><a href="method.html#cb24-5" tabindex="-1"></a>                 <span class="at">fill =</span> <span class="st">&quot;#2c7fb8&quot;</span>, </span>
<span id="cb24-6"><a href="method.html#cb24-6" tabindex="-1"></a>                 <span class="at">color =</span> <span class="st">&quot;white&quot;</span>, </span>
<span id="cb24-7"><a href="method.html#cb24-7" tabindex="-1"></a>                 <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb24-8"><a href="method.html#cb24-8" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">color =</span> <span class="st">&quot;darkblue&quot;</span>, <span class="at">linewidth =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb24-9"><a href="method.html#cb24-9" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb24-10"><a href="method.html#cb24-10" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución de Ventas Semanales&quot;</span>,</span>
<span id="cb24-11"><a href="method.html#cb24-11" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Ventas Semanales (USD)&quot;</span>,</span>
<span id="cb24-12"><a href="method.html#cb24-12" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Densidad&quot;</span></span>
<span id="cb24-13"><a href="method.html#cb24-13" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb24-14"><a href="method.html#cb24-14" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
</details>
<p><img src="bookdown-demo_files/figure-html/hist-ventas-semanales-1.png" width="672" /></p>
<ul>
<li>Veamos un diagrama de cajas y bigotes</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="method.html#cb25-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span></span>
<span id="cb25-2"><a href="method.html#cb25-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="st">&quot;&quot;</span>, <span class="at">y =</span> weekly_sales)) <span class="sc">+</span></span>
<span id="cb25-3"><a href="method.html#cb25-3" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#a6cee3&quot;</span>, <span class="at">color =</span> <span class="st">&quot;#1f78b4&quot;</span>, <span class="at">outlier.color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb25-4"><a href="method.html#cb25-4" tabindex="-1"></a>  <span class="fu">stat_summary</span>(</span>
<span id="cb25-5"><a href="method.html#cb25-5" tabindex="-1"></a>    <span class="at">fun =</span> mean,</span>
<span id="cb25-6"><a href="method.html#cb25-6" tabindex="-1"></a>    <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>,</span>
<span id="cb25-7"><a href="method.html#cb25-7" tabindex="-1"></a>    <span class="at">shape =</span> <span class="dv">20</span>,</span>
<span id="cb25-8"><a href="method.html#cb25-8" tabindex="-1"></a>    <span class="at">size =</span> <span class="dv">3</span>,</span>
<span id="cb25-9"><a href="method.html#cb25-9" tabindex="-1"></a>    <span class="at">color =</span> <span class="st">&quot;black&quot;</span></span>
<span id="cb25-10"><a href="method.html#cb25-10" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb25-11"><a href="method.html#cb25-11" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb25-12"><a href="method.html#cb25-12" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Diagrama de cajas y bigotes de ventas semanales&quot;</span>,</span>
<span id="cb25-13"><a href="method.html#cb25-13" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;&quot;</span>,</span>
<span id="cb25-14"><a href="method.html#cb25-14" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Ventas Semanales (USD)&quot;</span></span>
<span id="cb25-15"><a href="method.html#cb25-15" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb25-16"><a href="method.html#cb25-16" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
</details>
<p><img src="bookdown-demo_files/figure-html/prom-ventas-semanales-1.png" width="672" /></p>
<p>La distribución de weekly_sales es altamente asimétrica, con fuerte concentración de valores bajos y una cantidad significativa de valores extremos altos. Esto indica que aunque la mayoría de las tiendas tienen ventas semanales moderadas, existen algunas con ventas excepcionalmente altas que influyen notablemente en los estadísticos como la media y la desviación estándar.</p>
</div>
<div id="análisis-de-las-variables-características-independientes" class="section level3 hasAnchor" number="3.4.4">
<h3><span class="header-section-number">3.4.4</span> Análisis de las variables características (independientes)<a href="#an%C3%A1lisis-de-las-variables-caracter%C3%ADsticas-independientes" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Analizaremos el iniciamente las variables numéricas</p>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="method.html#cb26-1" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb26-2"><a href="method.html#cb26-2" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb26-3"><a href="method.html#cb26-3" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(temperature_c),</span>
<span id="cb26-4"><a href="method.html#cb26-4" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(temperature_c),</span>
<span id="cb26-5"><a href="method.html#cb26-5" tabindex="-1"></a>    <span class="at">ds =</span> <span class="fu">sd</span>(temperature_c),</span>
<span id="cb26-6"><a href="method.html#cb26-6" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(temperature_c),</span>
<span id="cb26-7"><a href="method.html#cb26-7" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(temperature_c),</span>
<span id="cb26-8"><a href="method.html#cb26-8" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(temperature_c),</span>
<span id="cb26-9"><a href="method.html#cb26-9" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(temperature_c, <span class="fl">0.25</span>),</span>
<span id="cb26-10"><a href="method.html#cb26-10" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(temperature_c, <span class="fl">0.75</span>),</span>
<span id="cb26-11"><a href="method.html#cb26-11" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(temperature_c)) <span class="sc">%&gt;%</span></span>
<span id="cb26-12"><a href="method.html#cb26-12" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">variable =</span> <span class="st">&quot;temperature_c&quot;</span>) <span class="ot">-&gt;</span> var_num_temp</span>
<span id="cb26-13"><a href="method.html#cb26-13" tabindex="-1"></a></span>
<span id="cb26-14"><a href="method.html#cb26-14" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb26-15"><a href="method.html#cb26-15" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb26-16"><a href="method.html#cb26-16" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(fuel_price_usd_per_l),</span>
<span id="cb26-17"><a href="method.html#cb26-17" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(fuel_price_usd_per_l),</span>
<span id="cb26-18"><a href="method.html#cb26-18" tabindex="-1"></a>    <span class="at">ds =</span> <span class="fu">sd</span>(fuel_price_usd_per_l),</span>
<span id="cb26-19"><a href="method.html#cb26-19" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(fuel_price_usd_per_l),</span>
<span id="cb26-20"><a href="method.html#cb26-20" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(fuel_price_usd_per_l),</span>
<span id="cb26-21"><a href="method.html#cb26-21" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(fuel_price_usd_per_l),</span>
<span id="cb26-22"><a href="method.html#cb26-22" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(fuel_price_usd_per_l, <span class="fl">0.25</span>),</span>
<span id="cb26-23"><a href="method.html#cb26-23" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(fuel_price_usd_per_l, <span class="fl">0.75</span>),</span>
<span id="cb26-24"><a href="method.html#cb26-24" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(fuel_price_usd_per_l)) <span class="sc">%&gt;%</span> </span>
<span id="cb26-25"><a href="method.html#cb26-25" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">variable =</span> <span class="st">&quot;fuel_price_usd_per_l&quot;</span>) <span class="ot">-&gt;</span> var_num_fuel</span>
<span id="cb26-26"><a href="method.html#cb26-26" tabindex="-1"></a></span>
<span id="cb26-27"><a href="method.html#cb26-27" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb26-28"><a href="method.html#cb26-28" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb26-29"><a href="method.html#cb26-29" tabindex="-1"></a>    <span class="at">n =</span> <span class="fu">length</span>(unemployment),</span>
<span id="cb26-30"><a href="method.html#cb26-30" tabindex="-1"></a>    <span class="at">media =</span> <span class="fu">mean</span>(unemployment),</span>
<span id="cb26-31"><a href="method.html#cb26-31" tabindex="-1"></a>    <span class="at">ds =</span> <span class="fu">sd</span>(unemployment),</span>
<span id="cb26-32"><a href="method.html#cb26-32" tabindex="-1"></a>    <span class="at">mediana =</span> <span class="fu">median</span>(unemployment),</span>
<span id="cb26-33"><a href="method.html#cb26-33" tabindex="-1"></a>    <span class="at">minimo =</span> <span class="fu">min</span>(unemployment),</span>
<span id="cb26-34"><a href="method.html#cb26-34" tabindex="-1"></a>    <span class="at">maximo =</span> <span class="fu">max</span>(unemployment),</span>
<span id="cb26-35"><a href="method.html#cb26-35" tabindex="-1"></a>    <span class="at">Q1 =</span> <span class="fu">quantile</span>(unemployment, <span class="fl">0.25</span>),</span>
<span id="cb26-36"><a href="method.html#cb26-36" tabindex="-1"></a>    <span class="at">Q3 =</span> <span class="fu">quantile</span>(unemployment, <span class="fl">0.75</span>),</span>
<span id="cb26-37"><a href="method.html#cb26-37" tabindex="-1"></a>    <span class="at">IQR =</span> <span class="fu">IQR</span>(unemployment)) <span class="sc">%&gt;%</span> </span>
<span id="cb26-38"><a href="method.html#cb26-38" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">variable =</span> <span class="st">&quot;unemployment&quot;</span>)<span class="ot">-&gt;</span> var_num_unemploy</span>
<span id="cb26-39"><a href="method.html#cb26-39" tabindex="-1"></a></span>
<span id="cb26-40"><a href="method.html#cb26-40" tabindex="-1"></a><span class="fu">bind_rows</span>(var_num_temp, var_num_fuel, var_num_unemploy) <span class="sc">%&gt;%</span></span>
<span id="cb26-41"><a href="method.html#cb26-41" tabindex="-1"></a>  <span class="fu">select</span>(variable, <span class="fu">everything</span>())</span></code></pre></div>
</details>
<pre><code>##               variable     n      media         ds    mediana     minimo    maximo        Q1         Q3         IQR
## 1        temperature_c 10774 15.7319782 9.92244608 16.9666667 -8.3666667 33.827778 7.5833333 24.1666667 16.58333333
## 2 fuel_price_usd_per_l 10774  0.7497458 0.05949359  0.7433805  0.6641289  1.107674 0.7082456  0.7814213  0.07317569
## 3         unemployment 10774  8.0820086 0.62435501  8.0990000  3.8790000  9.765000 7.7950000  8.3600000  0.56500000</code></pre>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="method.html#cb28-1" tabindex="-1"></a><span class="fu">library</span>(patchwork)</span>
<span id="cb28-2"><a href="method.html#cb28-2" tabindex="-1"></a></span>
<span id="cb28-3"><a href="method.html#cb28-3" tabindex="-1"></a><span class="co"># Boxplot de temperature_c</span></span>
<span id="cb28-4"><a href="method.html#cb28-4" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb28-5"><a href="method.html#cb28-5" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="st">&quot;&quot;</span>, <span class="at">y =</span> temperature_c)) <span class="sc">+</span></span>
<span id="cb28-6"><a href="method.html#cb28-6" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#1f77b4&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb28-7"><a href="method.html#cb28-7" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb28-8"><a href="method.html#cb28-8" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribucion de temperatura&quot;</span>,</span>
<span id="cb28-9"><a href="method.html#cb28-9" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Temperatura (°C)&quot;</span>,</span>
<span id="cb28-10"><a href="method.html#cb28-10" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;&quot;</span></span>
<span id="cb28-11"><a href="method.html#cb28-11" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb28-12"><a href="method.html#cb28-12" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb28-13"><a href="method.html#cb28-13" tabindex="-1"></a></span>
<span id="cb28-14"><a href="method.html#cb28-14" tabindex="-1"></a><span class="co"># Boxplot de fuel_price_usd_per_l</span></span>
<span id="cb28-15"><a href="method.html#cb28-15" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb28-16"><a href="method.html#cb28-16" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="st">&quot;&quot;</span>,<span class="at">y =</span> fuel_price_usd_per_l)) <span class="sc">+</span></span>
<span id="cb28-17"><a href="method.html#cb28-17" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#2ca02c&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb28-18"><a href="method.html#cb28-18" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb28-19"><a href="method.html#cb28-19" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribucion del precio del combustible&quot;</span>,</span>
<span id="cb28-20"><a href="method.html#cb28-20" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Precio (USD/litro)&quot;</span>,</span>
<span id="cb28-21"><a href="method.html#cb28-21" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;&quot;</span></span>
<span id="cb28-22"><a href="method.html#cb28-22" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb28-23"><a href="method.html#cb28-23" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb28-24"><a href="method.html#cb28-24" tabindex="-1"></a></span>
<span id="cb28-25"><a href="method.html#cb28-25" tabindex="-1"></a><span class="co"># Boxplot de unemployment</span></span>
<span id="cb28-26"><a href="method.html#cb28-26" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb28-27"><a href="method.html#cb28-27" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span><span class="st">&quot;&quot;</span>,<span class="at">y =</span> unemployment)) <span class="sc">+</span></span>
<span id="cb28-28"><a href="method.html#cb28-28" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#d62728&quot;</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb28-29"><a href="method.html#cb28-29" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb28-30"><a href="method.html#cb28-30" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribucion del desempleo&quot;</span>,</span>
<span id="cb28-31"><a href="method.html#cb28-31" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Tasa de desempleo (%)&quot;</span>,</span>
<span id="cb28-32"><a href="method.html#cb28-32" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;&quot;</span></span>
<span id="cb28-33"><a href="method.html#cb28-33" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb28-34"><a href="method.html#cb28-34" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span>
<span id="cb28-35"><a href="method.html#cb28-35" tabindex="-1"></a></span>
<span id="cb28-36"><a href="method.html#cb28-36" tabindex="-1"></a><span class="co"># Unir los tres gráficos en una sola visualización</span></span>
<span id="cb28-37"><a href="method.html#cb28-37" tabindex="-1"></a>p1 <span class="sc">+</span> p2 <span class="sc">+</span> p3  </span></code></pre></div>
</details>
<p><img src="bookdown-demo_files/figure-html/dc-var-ind-1.png" width="672" /></p>
<div class="admon-box ejercicio">
<div class="admon-title">
<span class="icon"></span> Ejercicio
</div>
<p>
La interpretación de la tabla y el gráfico quedan como ejercicio
</p>
</div>
<p>Ahora analizaremos las variables categóricas</p>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="method.html#cb29-1" tabindex="-1"></a><span class="co"># Tabla de frecuencias para type</span></span>
<span id="cb29-2"><a href="method.html#cb29-2" tabindex="-1"></a>tabla_type <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="method.html#cb29-3" tabindex="-1"></a>  <span class="fu">count</span>(type, <span class="at">name =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-4"><a href="method.html#cb29-4" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb29-5"><a href="method.html#cb29-5" tabindex="-1"></a>    <span class="at">Porcentaje =</span> <span class="fu">round</span>(Frecuencia <span class="sc">/</span> <span class="fu">sum</span>(Frecuencia) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>),</span>
<span id="cb29-6"><a href="method.html#cb29-6" tabindex="-1"></a>    <span class="at">Variable =</span> <span class="st">&quot;type&quot;</span>,</span>
<span id="cb29-7"><a href="method.html#cb29-7" tabindex="-1"></a>    <span class="at">Categoria =</span> <span class="fu">as.character</span>(type)</span>
<span id="cb29-8"><a href="method.html#cb29-8" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb29-9"><a href="method.html#cb29-9" tabindex="-1"></a>  <span class="fu">select</span>(Variable, Categoria, Frecuencia, Porcentaje)</span>
<span id="cb29-10"><a href="method.html#cb29-10" tabindex="-1"></a></span>
<span id="cb29-11"><a href="method.html#cb29-11" tabindex="-1"></a><span class="co"># Tabla de frecuencias para department</span></span>
<span id="cb29-12"><a href="method.html#cb29-12" tabindex="-1"></a>tabla_department <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb29-13"><a href="method.html#cb29-13" tabindex="-1"></a>  <span class="fu">count</span>(department, <span class="at">name =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-14"><a href="method.html#cb29-14" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb29-15"><a href="method.html#cb29-15" tabindex="-1"></a>    <span class="at">Porcentaje =</span> <span class="fu">round</span>(Frecuencia <span class="sc">/</span> <span class="fu">sum</span>(Frecuencia) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>),</span>
<span id="cb29-16"><a href="method.html#cb29-16" tabindex="-1"></a>    <span class="at">Variable =</span> <span class="st">&quot;department&quot;</span>,</span>
<span id="cb29-17"><a href="method.html#cb29-17" tabindex="-1"></a>    <span class="at">Categoria =</span> <span class="fu">as.character</span>(department)</span>
<span id="cb29-18"><a href="method.html#cb29-18" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb29-19"><a href="method.html#cb29-19" tabindex="-1"></a>  <span class="fu">select</span>(Variable, Categoria, Frecuencia, Porcentaje)</span>
<span id="cb29-20"><a href="method.html#cb29-20" tabindex="-1"></a></span>
<span id="cb29-21"><a href="method.html#cb29-21" tabindex="-1"></a><span class="co"># Tabla de frecuencias para is_holiday</span></span>
<span id="cb29-22"><a href="method.html#cb29-22" tabindex="-1"></a>tabla_holiday <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb29-23"><a href="method.html#cb29-23" tabindex="-1"></a>  <span class="fu">count</span>(is_holiday, <span class="at">name =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb29-24"><a href="method.html#cb29-24" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb29-25"><a href="method.html#cb29-25" tabindex="-1"></a>    <span class="at">Porcentaje =</span> <span class="fu">round</span>(Frecuencia <span class="sc">/</span> <span class="fu">sum</span>(Frecuencia) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>),</span>
<span id="cb29-26"><a href="method.html#cb29-26" tabindex="-1"></a>    <span class="at">Variable =</span> <span class="st">&quot;is_holiday&quot;</span>,</span>
<span id="cb29-27"><a href="method.html#cb29-27" tabindex="-1"></a>    <span class="at">Categoria =</span> <span class="fu">as.character</span>(is_holiday)</span>
<span id="cb29-28"><a href="method.html#cb29-28" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb29-29"><a href="method.html#cb29-29" tabindex="-1"></a>  <span class="fu">select</span>(Variable, Categoria, Frecuencia, Porcentaje)</span>
<span id="cb29-30"><a href="method.html#cb29-30" tabindex="-1"></a></span>
<span id="cb29-31"><a href="method.html#cb29-31" tabindex="-1"></a><span class="co"># Unir todas las tablas</span></span>
<span id="cb29-32"><a href="method.html#cb29-32" tabindex="-1"></a><span class="fu">bind_rows</span>(tabla_type, tabla_department, tabla_holiday)</span></code></pre></div>
</details>
<pre><code>##      Variable Categoria Frecuencia Porcentaje
## 1        type         A       9872      91.63
## 2        type         B        902       8.37
## 3  department         1        144       1.34
## 4  department         2        144       1.34
## 5  department         3        144       1.34
## 6  department         4        144       1.34
## 7  department         5        144       1.34
## 8  department         6        144       1.34
## 9  department         7        144       1.34
## 10 department         8        144       1.34
## 11 department         9        144       1.34
## 12 department        10        144       1.34
## 13 department        11        144       1.34
## 14 department        12        144       1.34
## 15 department        13        144       1.34
## 16 department        14        144       1.34
## 17 department        16        144       1.34
## 18 department        17        144       1.34
## 19 department        18        144       1.34
## 20 department        19        140       1.30
## 21 department        20        144       1.34
## 22 department        21        144       1.34
## 23 department        22        144       1.34
## 24 department        23        144       1.34
## 25 department        24        144       1.34
## 26 department        25        144       1.34
## 27 department        26        144       1.34
## 28 department        27        144       1.34
## 29 department        28        144       1.34
## 30 department        29        144       1.34
## 31 department        30        144       1.34
## 32 department        31        144       1.34
## 33 department        32        144       1.34
## 34 department        33        144       1.34
## 35 department        34        144       1.34
## 36 department        35        144       1.34
## 37 department        36        144       1.34
## 38 department        37        120       1.11
## 39 department        38        144       1.34
## 40 department        39          7       0.06
## 41 department        40        144       1.34
## 42 department        41        144       1.34
## 43 department        42        144       1.34
## 44 department        43          2       0.02
## 45 department        44        144       1.34
## 46 department        45        126       1.17
## 47 department        46        144       1.34
## 48 department        47        114       1.06
## 49 department        48         90       0.84
## 50 department        49        144       1.34
## 51 department        50         72       0.67
## 52 department        51         99       0.92
## 53 department        52        144       1.34
## 54 department        54        144       1.34
## 55 department        55        144       1.34
## 56 department        56        144       1.34
## 57 department        58        144       1.34
## 58 department        59        144       1.34
## 59 department        60        144       1.34
## 60 department        67        144       1.34
## 61 department        71        144       1.34
## 62 department        72        144       1.34
## 63 department        74        144       1.34
## 64 department        77         39       0.36
## 65 department        78         56       0.52
## 66 department        79        144       1.34
## 67 department        80        144       1.34
## 68 department        81        144       1.34
## 69 department        82        144       1.34
## 70 department        83        144       1.34
## 71 department        85        144       1.34
## 72 department        87        144       1.34
## 73 department        90        144       1.34
## 74 department        91        144       1.34
## 75 department        92        144       1.34
## 76 department        93        144       1.34
## 77 department        94        144       1.34
## 78 department        95        144       1.34
## 79 department        96        138       1.28
## 80 department        97        144       1.34
## 81 department        98        144       1.34
## 82 department        99        123       1.14
## 83 is_holiday     False      10732      99.61
## 84 is_holiday      True         42       0.39</code></pre>
<p>El <span class="math inline">\(91.63\%\)</span> de los registros pertenecen al tipo A, lo que indica que la gran mayoría de las observaciones están asociadas a este tipo de tienda, donde el tipo B representa solo el <span class="math inline">\(8.37\%\)</span> de los casos, lo cual puede sugerir que es menos común, más específico o de menor cobertura.</p>
<p>Existen más de <span class="math inline">\(80\)</span> categorías distintas. La mayoría de los departamentos tienen la misma frecuencia de <span class="math inline">\(144\)</span> observaciones (<span class="math inline">\(1.34\%\)</span>), lo que sugiere una distribución uniforme entre muchas de las categorías. Tambien nos inidica que hay una alta dispersión en las frecuencias de los departamentos, lo que indica que no todos los departamentos tienen el mismo nivel de actividad. Algunos departamentos deben ser tratados con precaución en los análisis inferenciales por su baja frecuencia.</p>
<p>Solo el <span class="math inline">\(0.39\%\)</span> de los registros corresponden a días festivos. Esto muestra una clara desproporción: los días feriados son poco frecuentes en los datos. Aunque son escasos, los registros en días festivos pueden tener un comportamiento distinto (por ejemplo, picos de ventas o cambios de demanda), por lo que deben analizarse por separado o con métodos robustos que no se vean afectados por el desbalance.</p>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="method.html#cb31-1" tabindex="-1"></a>tabla_type_b <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb31-2"><a href="method.html#cb31-2" tabindex="-1"></a>  <span class="fu">count</span>(type, <span class="at">name =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="method.html#cb31-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>(Frecuencia <span class="sc">/</span> <span class="fu">sum</span>(Frecuencia) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb31-4"><a href="method.html#cb31-4" tabindex="-1"></a>         <span class="at">Etiqueta =</span> <span class="fu">paste0</span>(Frecuencia, <span class="st">&quot; (&quot;</span>, Porcentaje, <span class="st">&quot;%)&quot;</span>))</span>
<span id="cb31-5"><a href="method.html#cb31-5" tabindex="-1"></a></span>
<span id="cb31-6"><a href="method.html#cb31-6" tabindex="-1"></a><span class="fu">ggplot</span>(tabla_type_b, <span class="fu">aes</span>(<span class="at">x =</span> type, <span class="at">y =</span> Frecuencia)) <span class="sc">+</span></span>
<span id="cb31-7"><a href="method.html#cb31-7" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">&quot;#008B8B&quot;</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb31-8"><a href="method.html#cb31-8" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Etiqueta), <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">5</span>) <span class="sc">+</span></span>
<span id="cb31-9"><a href="method.html#cb31-9" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> <span class="st">&quot;Distribución de la variable type&quot;</span>) <span class="sc">+</span> </span>
<span id="cb31-10"><a href="method.html#cb31-10" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.15</span>))) <span class="sc">+</span></span>
<span id="cb31-11"><a href="method.html#cb31-11" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Tipo de tienda&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Frecuencia (Porcentaje)&quot;</span>) <span class="sc">+</span></span>
<span id="cb31-12"><a href="method.html#cb31-12" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb31-13"><a href="method.html#cb31-13" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb31-14"><a href="method.html#cb31-14" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb31-15"><a href="method.html#cb31-15" tabindex="-1"></a>    <span class="at">strip.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;gray80&quot;</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb31-16"><a href="method.html#cb31-16" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>),</span>
<span id="cb31-17"><a href="method.html#cb31-17" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>()</span>
<span id="cb31-18"><a href="method.html#cb31-18" tabindex="-1"></a>  )</span></code></pre></div>
</details>
<p><img src="bookdown-demo_files/figure-html/db-cat-type-1.png" width="672" /></p>
<p>La gran mayoría de las observaciones (<span class="math inline">\(91.6\%\)</span>) corresponden al tipo A, con <span class="math inline">\(9872\)</span> registros. Solo el <span class="math inline">\(8.4\%\)</span> restante corresponde al tipo B, con <span class="math inline">\(902\)</span> registros.</p>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="method.html#cb32-1" tabindex="-1"></a><span class="co"># Crear tabla de frecuencias para department</span></span>
<span id="cb32-2"><a href="method.html#cb32-2" tabindex="-1"></a>tabla_department_b <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb32-3"><a href="method.html#cb32-3" tabindex="-1"></a>  <span class="fu">count</span>(department, <span class="at">name =</span> <span class="st">&quot;Frecuencia&quot;</span>) <span class="sc">%&gt;%</span></span>
<span id="cb32-4"><a href="method.html#cb32-4" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> <span class="fu">round</span>(Frecuencia <span class="sc">/</span> <span class="fu">sum</span>(Frecuencia) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb32-5"><a href="method.html#cb32-5" tabindex="-1"></a>         <span class="at">Etiqueta =</span> <span class="fu">paste0</span>(Frecuencia, <span class="st">&quot; (&quot;</span>, Porcentaje, <span class="st">&quot;%)&quot;</span>))</span>
<span id="cb32-6"><a href="method.html#cb32-6" tabindex="-1"></a></span>
<span id="cb32-7"><a href="method.html#cb32-7" tabindex="-1"></a><span class="co"># Gráfico</span></span>
<span id="cb32-8"><a href="method.html#cb32-8" tabindex="-1"></a><span class="fu">ggplot</span>(tabla_department_b, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(department), <span class="at">y =</span> Frecuencia)) <span class="sc">+</span></span>
<span id="cb32-9"><a href="method.html#cb32-9" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">fill =</span> <span class="st">&quot;#008B8B&quot;</span>, <span class="at">width =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb32-10"><a href="method.html#cb32-10" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> Etiqueta), <span class="at">hjust =</span> <span class="sc">-</span><span class="fl">0.1</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb32-11"><a href="method.html#cb32-11" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> <span class="st">&quot;Distribución de la variable department&quot;</span>) <span class="sc">+</span> </span>
<span id="cb32-12"><a href="method.html#cb32-12" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">expansion</span>(<span class="at">mult =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.10</span>))) <span class="sc">+</span></span>
<span id="cb32-13"><a href="method.html#cb32-13" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Departamento&quot;</span>, <span class="at">y =</span> <span class="st">&quot;Frecuencia (Porcentaje)&quot;</span>) <span class="sc">+</span></span>
<span id="cb32-14"><a href="method.html#cb32-14" tabindex="-1"></a>  <span class="fu">coord_flip</span>() <span class="sc">+</span></span>
<span id="cb32-15"><a href="method.html#cb32-15" tabindex="-1"></a>  <span class="fu">theme_bw</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb32-16"><a href="method.html#cb32-16" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb32-17"><a href="method.html#cb32-17" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb32-18"><a href="method.html#cb32-18" tabindex="-1"></a>    <span class="at">strip.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">&quot;gray80&quot;</span>, <span class="at">color =</span> <span class="cn">NA</span>),</span>
<span id="cb32-19"><a href="method.html#cb32-19" tabindex="-1"></a>    <span class="at">strip.text =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>),</span>
<span id="cb32-20"><a href="method.html#cb32-20" tabindex="-1"></a>    <span class="at">panel.grid.major.y =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb32-21"><a href="method.html#cb32-21" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>)  </span>
<span id="cb32-22"><a href="method.html#cb32-22" tabindex="-1"></a>  )</span></code></pre></div>
</details>
<p><img src="bookdown-demo_files/figure-html/db-cat-dep-1.png" width="672" /></p>
<div class="admon-box ejercicio">
<div class="admon-title">
<span class="icon"></span> Ejercicio
</div>
<ol>
<li>
Interpreta el gráfico de la variable <code>department</code> y muestra únicamente las 10 categorías con mayor porcentaje.
</li>
<li>
Realiza el gráfico para la variable <code>is_holiday</code> e interprétalo.
</li>
</ol>
</div>
</div>
<div id="análisis-exploratorio-bivariado" class="section level3 hasAnchor" number="3.4.5">
<h3><span class="header-section-number">3.4.5</span> Análisis exploratorio bivariado<a href="#an%C3%A1lisis-exploratorio-bivariado" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>Realizaremos la comparacion de la variable <code>weekly_sales</code> con respecto a las variables numéricas independientes.</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="method.html#cb33-1" tabindex="-1"></a><span class="co"># Diagrama de dispersión: weekly_sales vs temperature_c</span></span>
<span id="cb33-2"><a href="method.html#cb33-2" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb33-3"><a href="method.html#cb33-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> temperature_c, <span class="at">y =</span> weekly_sales)) <span class="sc">+</span></span>
<span id="cb33-4"><a href="method.html#cb33-4" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>, <span class="at">color =</span> <span class="st">&quot;#1E90FF&quot;</span>) <span class="sc">+</span></span>
<span id="cb33-5"><a href="method.html#cb33-5" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb33-6"><a href="method.html#cb33-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Temperatura (°C)&quot;</span>,</span>
<span id="cb33-7"><a href="method.html#cb33-7" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Ventas semanales (uds)&quot;</span></span>
<span id="cb33-8"><a href="method.html#cb33-8" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb33-9"><a href="method.html#cb33-9" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb33-10"><a href="method.html#cb33-10" tabindex="-1"></a>  <span class="fu">facet_grid</span>(.<span class="sc">~</span> <span class="st">&quot;Dispersión entre Weekly Sales y Temperature (°C)&quot;</span>)</span></code></pre></div>
</details>
<p><img src="bookdown-demo_files/figure-html/disp-1.png" width="672" /></p>
<p>Los puntos están muy dispersos a lo largo de todo el eje de temperatura (desde aproximadamente <span class="math inline">\(-10 °C\)</span> hasta <span class="math inline">\(35 °C\)</span>), pero no muestran una tendencia clara ascendente ni descendente. La mayoría de las tiendas se agrupan entre temperaturas de <span class="math inline">\(0 °C\)</span> y <span class="math inline">\(30 °C\)</span>, lo que es esperado para regiones con climas templados. A lo largo del eje de temperatura, las ventas semanales presentan alta variabilidad, es decir, hay tiendas con ventas altas y bajas a cualquier temperatura.</p>
<p>Existen varios puntos con ventas muy elevadas (por encima de 200.000), que podrían representar eventos especiales, promociones, festividades, etc. También se observan múltiples valores cercanos a cero, lo cual podría indicar tiendas cerradas, errores en la base de datos, o semanas sin ventas.</p>
<p>No se evidencia una relación lineal clara entre la temperatura y las ventas semanales. La temperatura parece tener un efecto mínimo o nulo sobre las ventas, lo cual sugiere que otras variables podrían tener mayor peso explicativo en el comportamiento de <code>weekly_sales</code>.</p>
<div class="admon-box ejercicio">
<div class="admon-title">
<span class="icon"></span> Ejercicio
</div>
<p>
Realiza el diagrama de dispersión para la variable <code>weekly_sales</code> con respecto a las variables <code>fuel_price_usd_per_l</code> y <code>unemployment</code> e interprétalos.
</p>
</div>
<ul>
<li>Realizaremos la comparacion de la variable <code>weekly_sales</code> con respecto a las variables categóricas independientes.</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="method.html#cb34-1" tabindex="-1"></a><span class="co"># Agrupación por &#39;type&#39;</span></span>
<span id="cb34-2"><a href="method.html#cb34-2" tabindex="-1"></a>type_week <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb34-3"><a href="method.html#cb34-3" tabindex="-1"></a>  <span class="fu">group_by</span>(type) <span class="sc">%&gt;%</span></span>
<span id="cb34-4"><a href="method.html#cb34-4" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">length</span>(weekly_sales),</span>
<span id="cb34-5"><a href="method.html#cb34-5" tabindex="-1"></a>            <span class="at">media =</span> <span class="fu">mean</span>(weekly_sales),</span>
<span id="cb34-6"><a href="method.html#cb34-6" tabindex="-1"></a>            <span class="at">ds =</span> <span class="fu">sd</span>(weekly_sales),</span>
<span id="cb34-7"><a href="method.html#cb34-7" tabindex="-1"></a>            <span class="at">mediana =</span> <span class="fu">median</span>(weekly_sales),</span>
<span id="cb34-8"><a href="method.html#cb34-8" tabindex="-1"></a>            <span class="at">minimo =</span> <span class="fu">min</span>(weekly_sales),</span>
<span id="cb34-9"><a href="method.html#cb34-9" tabindex="-1"></a>            <span class="at">maximo =</span> <span class="fu">max</span>(weekly_sales),</span>
<span id="cb34-10"><a href="method.html#cb34-10" tabindex="-1"></a>            <span class="at">Q1 =</span> <span class="fu">quantile</span>(weekly_sales, <span class="fl">0.25</span>),</span>
<span id="cb34-11"><a href="method.html#cb34-11" tabindex="-1"></a>            <span class="at">Q3 =</span> <span class="fu">quantile</span>(weekly_sales, <span class="fl">0.75</span>),</span>
<span id="cb34-12"><a href="method.html#cb34-12" tabindex="-1"></a>            <span class="at">IQR =</span> <span class="fu">IQR</span>(weekly_sales)) <span class="sc">%&gt;%</span></span>
<span id="cb34-13"><a href="method.html#cb34-13" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">variable =</span> <span class="st">&quot;type&quot;</span>, <span class="at">niveles =</span> <span class="fu">as.character</span>(type)) <span class="sc">%&gt;%</span></span>
<span id="cb34-14"><a href="method.html#cb34-14" tabindex="-1"></a>  <span class="fu">select</span>(variable, niveles, <span class="fu">everything</span>(), <span class="sc">-</span>type)</span>
<span id="cb34-15"><a href="method.html#cb34-15" tabindex="-1"></a></span>
<span id="cb34-16"><a href="method.html#cb34-16" tabindex="-1"></a><span class="co"># Agrupación por &#39;store&#39;</span></span>
<span id="cb34-17"><a href="method.html#cb34-17" tabindex="-1"></a>store_week <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb34-18"><a href="method.html#cb34-18" tabindex="-1"></a>  <span class="fu">group_by</span>(store) <span class="sc">%&gt;%</span></span>
<span id="cb34-19"><a href="method.html#cb34-19" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">length</span>(weekly_sales),</span>
<span id="cb34-20"><a href="method.html#cb34-20" tabindex="-1"></a>            <span class="at">media =</span> <span class="fu">mean</span>(weekly_sales),</span>
<span id="cb34-21"><a href="method.html#cb34-21" tabindex="-1"></a>            <span class="at">ds =</span> <span class="fu">sd</span>(weekly_sales),</span>
<span id="cb34-22"><a href="method.html#cb34-22" tabindex="-1"></a>            <span class="at">mediana =</span> <span class="fu">median</span>(weekly_sales),</span>
<span id="cb34-23"><a href="method.html#cb34-23" tabindex="-1"></a>            <span class="at">minimo =</span> <span class="fu">min</span>(weekly_sales),</span>
<span id="cb34-24"><a href="method.html#cb34-24" tabindex="-1"></a>            <span class="at">maximo =</span> <span class="fu">max</span>(weekly_sales),</span>
<span id="cb34-25"><a href="method.html#cb34-25" tabindex="-1"></a>            <span class="at">Q1 =</span> <span class="fu">quantile</span>(weekly_sales, <span class="fl">0.25</span>),</span>
<span id="cb34-26"><a href="method.html#cb34-26" tabindex="-1"></a>            <span class="at">Q3 =</span> <span class="fu">quantile</span>(weekly_sales, <span class="fl">0.75</span>),</span>
<span id="cb34-27"><a href="method.html#cb34-27" tabindex="-1"></a>            <span class="at">IQR =</span> <span class="fu">IQR</span>(weekly_sales)) <span class="sc">%&gt;%</span></span>
<span id="cb34-28"><a href="method.html#cb34-28" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">variable =</span> <span class="st">&quot;store&quot;</span>, <span class="at">niveles =</span> <span class="fu">as.character</span>(store)) <span class="sc">%&gt;%</span></span>
<span id="cb34-29"><a href="method.html#cb34-29" tabindex="-1"></a>  <span class="fu">select</span>(variable, niveles, <span class="fu">everything</span>(), <span class="sc">-</span>store)</span>
<span id="cb34-30"><a href="method.html#cb34-30" tabindex="-1"></a></span>
<span id="cb34-31"><a href="method.html#cb34-31" tabindex="-1"></a><span class="co"># Agrupación por &#39;department&#39;</span></span>
<span id="cb34-32"><a href="method.html#cb34-32" tabindex="-1"></a>dep_week <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb34-33"><a href="method.html#cb34-33" tabindex="-1"></a>  <span class="fu">group_by</span>(department) <span class="sc">%&gt;%</span></span>
<span id="cb34-34"><a href="method.html#cb34-34" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">length</span>(weekly_sales),</span>
<span id="cb34-35"><a href="method.html#cb34-35" tabindex="-1"></a>            <span class="at">media =</span> <span class="fu">mean</span>(weekly_sales),</span>
<span id="cb34-36"><a href="method.html#cb34-36" tabindex="-1"></a>            <span class="at">ds =</span> <span class="fu">sd</span>(weekly_sales),</span>
<span id="cb34-37"><a href="method.html#cb34-37" tabindex="-1"></a>            <span class="at">mediana =</span> <span class="fu">median</span>(weekly_sales),</span>
<span id="cb34-38"><a href="method.html#cb34-38" tabindex="-1"></a>            <span class="at">minimo =</span> <span class="fu">min</span>(weekly_sales),</span>
<span id="cb34-39"><a href="method.html#cb34-39" tabindex="-1"></a>            <span class="at">maximo =</span> <span class="fu">max</span>(weekly_sales),</span>
<span id="cb34-40"><a href="method.html#cb34-40" tabindex="-1"></a>            <span class="at">Q1 =</span> <span class="fu">quantile</span>(weekly_sales, <span class="fl">0.25</span>),</span>
<span id="cb34-41"><a href="method.html#cb34-41" tabindex="-1"></a>            <span class="at">Q3 =</span> <span class="fu">quantile</span>(weekly_sales, <span class="fl">0.75</span>),</span>
<span id="cb34-42"><a href="method.html#cb34-42" tabindex="-1"></a>            <span class="at">IQR =</span> <span class="fu">IQR</span>(weekly_sales)) <span class="sc">%&gt;%</span></span>
<span id="cb34-43"><a href="method.html#cb34-43" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">variable =</span> <span class="st">&quot;department&quot;</span>, <span class="at">niveles =</span> <span class="fu">as.character</span>(department)) <span class="sc">%&gt;%</span></span>
<span id="cb34-44"><a href="method.html#cb34-44" tabindex="-1"></a>  <span class="fu">select</span>(variable, niveles, <span class="fu">everything</span>(), <span class="sc">-</span>department)</span>
<span id="cb34-45"><a href="method.html#cb34-45" tabindex="-1"></a></span>
<span id="cb34-46"><a href="method.html#cb34-46" tabindex="-1"></a><span class="co"># Agrupación por &#39;is_holiday&#39;</span></span>
<span id="cb34-47"><a href="method.html#cb34-47" tabindex="-1"></a>holi_week <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb34-48"><a href="method.html#cb34-48" tabindex="-1"></a>  <span class="fu">group_by</span>(is_holiday) <span class="sc">%&gt;%</span></span>
<span id="cb34-49"><a href="method.html#cb34-49" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">length</span>(weekly_sales),</span>
<span id="cb34-50"><a href="method.html#cb34-50" tabindex="-1"></a>            <span class="at">media =</span> <span class="fu">mean</span>(weekly_sales),</span>
<span id="cb34-51"><a href="method.html#cb34-51" tabindex="-1"></a>            <span class="at">ds =</span> <span class="fu">sd</span>(weekly_sales),</span>
<span id="cb34-52"><a href="method.html#cb34-52" tabindex="-1"></a>            <span class="at">mediana =</span> <span class="fu">median</span>(weekly_sales),</span>
<span id="cb34-53"><a href="method.html#cb34-53" tabindex="-1"></a>            <span class="at">minimo =</span> <span class="fu">min</span>(weekly_sales),</span>
<span id="cb34-54"><a href="method.html#cb34-54" tabindex="-1"></a>            <span class="at">maximo =</span> <span class="fu">max</span>(weekly_sales),</span>
<span id="cb34-55"><a href="method.html#cb34-55" tabindex="-1"></a>            <span class="at">Q1 =</span> <span class="fu">quantile</span>(weekly_sales, <span class="fl">0.25</span>),</span>
<span id="cb34-56"><a href="method.html#cb34-56" tabindex="-1"></a>            <span class="at">Q3 =</span> <span class="fu">quantile</span>(weekly_sales, <span class="fl">0.75</span>),</span>
<span id="cb34-57"><a href="method.html#cb34-57" tabindex="-1"></a>            <span class="at">IQR =</span> <span class="fu">IQR</span>(weekly_sales)) <span class="sc">%&gt;%</span></span>
<span id="cb34-58"><a href="method.html#cb34-58" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">variable =</span> <span class="st">&quot;is_holiday&quot;</span>, <span class="at">niveles =</span> <span class="fu">as.character</span>(is_holiday)) <span class="sc">%&gt;%</span></span>
<span id="cb34-59"><a href="method.html#cb34-59" tabindex="-1"></a>  <span class="fu">select</span>(variable, niveles, <span class="fu">everything</span>(), <span class="sc">-</span>is_holiday)</span>
<span id="cb34-60"><a href="method.html#cb34-60" tabindex="-1"></a></span>
<span id="cb34-61"><a href="method.html#cb34-61" tabindex="-1"></a><span class="co"># Unión de todas las tablas</span></span>
<span id="cb34-62"><a href="method.html#cb34-62" tabindex="-1"></a><span class="fu">bind_rows</span>(type_week, store_week, dep_week, holi_week)</span></code></pre></div>
</details>
<pre><code>## # A tibble: 96 × 11
##    variable niveles     n  media     ds mediana minimo  maximo    Q1     Q3    IQR
##    &lt;chr&gt;    &lt;chr&gt;   &lt;int&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;
##  1 type     A        9872 23675. 30129.  11944.  -1098 293966. 3862. 31982. 28120.
##  2 type     B         902 25697. 31156.  13336.   -798 232559. 3998. 38195. 34197.
##  3 store    1         901 20897. 26994.   9775.   -698 140504. 3199  30186. 26987.
##  4 store    2         897 26517. 32682.  13765.  -1098 178983. 4892. 34612. 29720.
##  5 store    4         901 26127. 31202.  13064.    -88 165766. 4571. 35552. 30982.
##  6 store    6         894 21561. 23658.  13201.   -698 119812. 4284. 30962. 26678.
##  7 store    10        902 25697. 31156.  13336.   -798 232559. 3998. 38195. 34197.
##  8 store    13        913 25664. 31499.  13050.    -98 166872. 4396. 34686. 30290.
##  9 store    14        885 30384. 40467.  14793.   -498 293966. 4386  37384. 32998.
## 10 store    19        906 19931. 24662.  11092.   -449 147449. 3695. 24861. 21166.
## # ℹ 86 more rows</code></pre>
<p>La variable <code>type</code> clasifica las tiendas en dos categorías: A y B, donde el <span class="math inline">\(91.6\%\)</span> de los registros corresponde a tiendas tipo A (<span class="math inline">\(n = 9872\)</span>) y solo el <span class="math inline">\(8.4\%\)</span> a tipo B (<span class="math inline">\(n = 902\)</span>). A pesar de su menor frecuencia, las tiendas tipo B presentan una media de ventas semanales más alta de <span class="math inline">\(25696.68\)</span> usd (DS = <span class="math inline">\(31155.87\)</span> usd) comparada con las de tipo A de <span class="math inline">\(23674.67\)</span> usd (DS = <span class="math inline">\(30129.41\)</span> usd). El <span class="math inline">\(50\%\)</span> de las tiendas tipo B tiene ventas semanales por debajo de 13336.08 usd, mientras que en las tipo A este valor es de <span class="math inline">\(11943.920\)</span> usd. Además, las tiendas tipo B presentan un rango intercuartílico más amplio (IQR = <span class="math inline">\(34196.80\)</span> usd) en comparación con las tipo A (IQR = <span class="math inline">\(28119.99\)</span> usd), lo que indica una mayor dispersión en la distribución de sus ventas semanales. Estos datos sugieren que, aunque las tiendas tipo B son menos frecuentes, tienden a mostrar un mejor desempeño en ventas, acompañado de una mayor variabilidad en sus resultados.</p>
<p>La variable <code>is_holiday</code> identifica si una semana corresponde a un periodo festivo (<code>True</code>) o no (<code>False</code>). La mayoría de los registros (<span class="math inline">\(99.6\%\)</span>) corresponden a semanas no festivas (<span class="math inline">\(n = 10732\)</span>), mientras que solo el <span class="math inline">\(0.4\%\)</span> pertenece a semanas festivas (<span class="math inline">\(n = 42\)</span>). Las semanas no festivas presentan una media de ventas semanales de <span class="math inline">\(23934.91 usd\)</span> (DS = <span class="math inline">\(30,244.33\)</span> usd), significativamente superior a la de las semanas festivas, que registran en promedio apenas <span class="math inline">\(600.55\)</span> usd (DS = <span class="math inline">\(1054.73\)</span> usd). El <span class="math inline">\(50\%\)</span> de las semanas no festivas tiene ventas por debajo de <span class="math inline">\(12135.16\)</span> usd, mientras que en las semanas festivas ese valor cae a tan solo <span class="math inline">\(37.50\)</span> usd. El rango intercuartílico (IQR) también es mucho más amplio en las semanas no festivas (<span class="math inline">\(28555.85\)</span> usd) que en las festivas (<span class="math inline">\(928\)</span> usd), lo que indica no solo un volumen mayor de ventas en semanas regulares, sino también una mayor variabilidad. Estos resultados reflejan que las semanas festivas se asocian con un desempeño comercial considerablemente menor en comparación con las semanas ordinarias.</p>
<div class="admon-box ejercicio">
<div class="admon-title">
<span class="icon"></span> Ejercicio
</div>
<p>
Realiza la interpretación para la variable <code>weekly_sales</code> con respecto a las variables <code>department</code> y <code>store</code>.
</p>
</div>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="method.html#cb36-1" tabindex="-1"></a><span class="co"># boxplot: weekly_sales vs tipo</span></span>
<span id="cb36-2"><a href="method.html#cb36-2" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb36-3"><a href="method.html#cb36-3" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> type, <span class="at">y =</span> weekly_sales)) <span class="sc">+</span></span>
<span id="cb36-4"><a href="method.html#cb36-4" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">fill =</span> <span class="st">&quot;#87CEFA&quot;</span>, <span class="at">outlier.colour =</span> <span class="st">&quot;red&quot;</span>, <span class="at">outlier.shape =</span> <span class="dv">16</span>) <span class="sc">+</span></span>
<span id="cb36-5"><a href="method.html#cb36-5" tabindex="-1"></a>  <span class="fu">stat_summary</span>(<span class="at">fun =</span> mean, <span class="at">geom =</span> <span class="st">&quot;point&quot;</span>, <span class="at">shape =</span> <span class="dv">18</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">color =</span> <span class="st">&quot;darkblue&quot;</span>) <span class="sc">+</span></span>
<span id="cb36-6"><a href="method.html#cb36-6" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&quot;Tipo de tienda&quot;</span>,</span>
<span id="cb36-7"><a href="method.html#cb36-7" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Ventas semanales (usd)&quot;</span></span>
<span id="cb36-8"><a href="method.html#cb36-8" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb36-9"><a href="method.html#cb36-9" tabindex="-1"></a>  <span class="fu">theme_bw</span>()<span class="sc">+</span></span>
<span id="cb36-10"><a href="method.html#cb36-10" tabindex="-1"></a>  <span class="fu">facet_grid</span>(.<span class="sc">~</span><span class="st">&quot;Distribución de Weekly Sales por tipo de tienda&quot;</span>)</span></code></pre></div>
</details>
<p><img src="bookdown-demo_files/figure-html/comp_boxplot-1.png" width="672" /></p>
<p>El gráfico compara las ventas semanales de las tiendas tipo A y B. Se observa que, aunque hay muchas más tiendas tipo A, las tiendas tipo B presentan un promedio de ventas semanales ligeramente más alto, lo cual se refleja en el rombo azul más elevado en su caja. Además, las tiendas tipo B muestran mayor variación en sus ventas, es decir, algunas venden mucho y otras menos, mientras que las tipo A tienen un comportamiento un poco más concentrado. Los puntos rojos sobre las cajas indican semanas con ventas excepcionalmente altas, siendo más frecuentes en las tiendas tipo A. En conjunto, esto sugiere que las tiendas tipo B, aunque menos numerosas, tienden a tener un mejor desempeño promedio, pero con mayor variabilidad; mientras que las tiendas tipo A tienen más casos extremos de ventas muy altas.</p>
<div class="admon-box ejercicio">
<div class="admon-title">
<span class="icon"></span> Ejercicio
</div>
<ol>
<li>
Realiza la grafica para la variable <code>weekly_sales</code> con respecto a las variables <code>department</code>, <code>is_holiday</code> y <code>store</code>. Interprete
<li>
Realiza el análisis bivariado con respecto a las variables independiente
&lt;&gt;
</ol>
</div>
<div class="admon-box nota">
<div class="admon-title">
<span class="icon"></span> Paquete <code>GGally</code>
</div>
<p>
<p>El paquete <code>GGally</code> es una extensión de <code>ggplot2</code> que facilita la creación de gráficos multivariados para análisis exploratorio de datos. Una de sus funciones más utilizadas es <code>ggpairs()</code>, que permite visualizar simultáneamente relaciones entre varias variables, tanto numéricas como categóricas, mediante:</p>
<ul>
<li>Diagramas de dispersión (scatterplots),</li>
<li>Histogramas o densidades en la diagonal,</li>
<li>Correlaciones entre pares de variables numéricas.</li>
</ul>
<p>Esto es especialmente útil para detectar patrones, asociaciones o valores atípicos en conjuntos de datos con múltiples variables.</p>
<p>Su instalación y carga del paquete</p>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="method.html#cb37-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;GGally&quot;</span>)</span>
<span id="cb37-2"><a href="method.html#cb37-2" tabindex="-1"></a><span class="fu">library</span>(GGally)</span></code></pre></div>
</details>
</p>
</div>
<p>Modo de uso del paquete <code>GGally</code>:</p>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="method.html#cb38-1" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb38-2"><a href="method.html#cb38-2" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb38-3"><a href="method.html#cb38-3" tabindex="-1"></a>  <span class="fu">ggpairs</span>()</span></code></pre></div>
</details>
<p><img src="bookdown-demo_files/figure-html/ggally-1.png" width="672" /></p>
<div class="admon-box ejercicio">
<div class="admon-title">
<span class="icon"></span> Ejercicio
</div>
<p>
Menciona los errores que puedes encontrar en el gráfico
</p>
</div>
<div id="análisis-explotario-con-variable-respuesta-categórica" class="section level2 hasAnchor" number="3.5">
<h2><span class="header-section-number">3.5</span> Análisis explotario con variable respuesta categórica<a href="#an%C3%A1lisis-explotario-con-variable-respuesta-categ%C3%B3rica" class="anchor-section" aria-label="Anchor link to header"></a></h2>

</div>
            </section>

          </div>
        </div>
      </div>
<a href="literature.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="applications.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/rstudio/bookdown-demo/edit/master/03-method.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
