<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 7 Regresión lineal simple | Notas de métodos estadísticos</title>
  <meta name="description" content="Notas de clase de métodos estadísticos." />
  <meta name="generator" content="bookdown 0.43 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 7 Regresión lineal simple | Notas de métodos estadísticos" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Notas de clase de métodos estadísticos." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 7 Regresión lineal simple | Notas de métodos estadísticos" />
  
  <meta name="twitter:description" content="Notas de clase de métodos estadísticos." />
  

<meta name="author" content="Carlos de Oro Aguado" />


<meta name="date" content="2025-09-10" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="correglin.html"/>
<link rel="next" href="referencias-1.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/codefolding-lua-1.1/codefolding-lua.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Notas de métodos estadísticos</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Asignatura</a></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introducción</a>
<ul>
<li class="chapter" data-level="1.1" data-path="07-rls.html"><a href="#introducci%C3%B3n-a-r-y-rstudio"><i class="fa fa-check"></i><b>1.1</b> Introducción a R y RStudio</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="07-rls.html"><a href="#qu%C3%A9-es-r"><i class="fa fa-check"></i><b>1.1.1</b> ¿Qué es R?</a></li>
<li class="chapter" data-level="1.1.2" data-path="07-rls.html"><a href="#qu%C3%A9-es-rstudio"><i class="fa fa-check"></i><b>1.1.2</b> ¿Qué es RStudio?</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="07-rls.html"><a href="#introducci%C3%B3n-a-git-y-github"><i class="fa fa-check"></i><b>1.2</b> Introducción a Git y GitHub</a>
<ul>
<li class="chapter" data-level="1.2.1" data-path="07-rls.html"><a href="#qu%C3%A9-es-git"><i class="fa fa-check"></i><b>1.2.1</b> ¿Qué es Git?</a></li>
<li class="chapter" data-level="1.2.2" data-path="07-rls.html"><a href="#qu%C3%A9-es-github"><i class="fa fa-check"></i><b>1.2.2</b> ¿Qué es GitHub?</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="07-rls.html"><a href="#introducci%C3%B3n-a-tidyverse"><i class="fa fa-check"></i><b>1.3</b> Introducción a Tidyverse</a>
<ul>
<li class="chapter" data-level="1.3.1" data-path="07-rls.html"><a href="#representaci%C3%B3n-visual-del-ecosistema-tidyverse"><i class="fa fa-check"></i><b>1.3.1</b> Representación visual del ecosistema Tidyverse</a></li>
<li class="chapter" data-level="1.3.2" data-path="intro.html"><a href="intro.html#principales-paquetes-del-tidyverse"><i class="fa fa-check"></i><b>1.3.2</b> Principales paquetes del Tidyverse</a></li>
<li class="chapter" data-level="1.3.3" data-path="07-rls.html"><a href="#instalaci%C3%B3n-del-tidyverse-en-r"><i class="fa fa-check"></i><b>1.3.3</b> Instalación del Tidyverse en R</a></li>
</ul></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#pasos-para-publicar-un-libro-bookdown-en-github-pages"><i class="fa fa-check"></i><b>1.4</b> Pasos para publicar un libro <code>bookdown</code> en GitHub Pages</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="07-rls.html"><a href="#video-paso-a-paso-de-la-publicaci%C3%B3n-del-libro-en-github-pages"><i class="fa fa-check"></i><b>1.4.1</b> Video paso a paso de la publicación del libro en GitHub Pages</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="reglas.html"><a href="reglas.html"><i class="fa fa-check"></i><b>2</b> Reglas de curso y diagnostico</a>
<ul>
<li class="chapter" data-level="2.1" data-path="reglas.html"><a href="reglas.html#reglas-de-las-clases"><i class="fa fa-check"></i><b>2.1</b> Reglas de las clases</a></li>
<li class="chapter" data-level="2.2" data-path="07-rls.html"><a href="#pol%C3%ADtica-de-evaluaci%C3%B3n-y-normas-de-integridad-acad%C3%A9mica"><i class="fa fa-check"></i><b>2.2</b> Política de evaluación y normas de integridad académica</a></li>
<li class="chapter" data-level="2.3" data-path="reglas.html"><a href="reglas.html#fechas-de-taller-y-examenes"><i class="fa fa-check"></i><b>2.3</b> Fechas de taller y examenes</a></li>
<li class="chapter" data-level="2.4" data-path="07-rls.html"><a href="#programaci%C3%B3n-del-curso-por-unidad"><i class="fa fa-check"></i><b>2.4</b> Programación del curso por unidad</a></li>
<li class="chapter" data-level="2.5" data-path="reglas.html"><a href="reglas.html#referencias"><i class="fa fa-check"></i><b>2.5</b> Referencias</a></li>
<li class="chapter" data-level="2.6" data-path="07-rls.html"><a href="#terminos-b%C3%A1sicos-de-la-estad%C3%ADstica"><i class="fa fa-check"></i><b>2.6</b> Terminos básicos de la estadística</a></li>
<li class="chapter" data-level="2.7" data-path="07-rls.html"><a href="#diagnostico-de-estad%C3%ADstica-b%C3%A1sica"><i class="fa fa-check"></i><b>2.7</b> Diagnostico de estadística básica</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="eda.html"><a href="eda.html"><i class="fa fa-check"></i><b>3</b> Análisis exploratorio de datos (EDA)</a>
<ul>
<li class="chapter" data-level="3.1" data-path="07-rls.html"><a href="#cu%C3%A1ndo-debo-utilizarlo"><i class="fa fa-check"></i><b>3.1</b> ¿Cuándo debo utilizarlo?</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="07-rls.html"><a href="#tipos-de-an%C3%A1lisis-exploratorio"><i class="fa fa-check"></i><b>3.1.1</b> Tipos de análisis exploratorio:</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="07-rls.html"><a href="#representaci%C3%B3n-de-datos-seg%C3%BAn-su-naturaleza"><i class="fa fa-check"></i><b>3.2</b> Representación de datos según su naturaleza</a></li>
<li class="chapter" data-level="3.3" data-path="07-rls.html"><a href="#presentaci%C3%B3n-y-an%C3%A1lisis-de-la-informaci%C3%B3n-en-estudios-descriptivos"><i class="fa fa-check"></i><b>3.3</b> Presentación y análisis de la información en estudios descriptivos</a></li>
<li class="chapter" data-level="3.4" data-path="07-rls.html"><a href="#an%C3%A1lisis-explotario-con-variable-respuesta-num%C3%A9rica"><i class="fa fa-check"></i><b>3.4</b> Análisis explotario con variable respuesta numérica</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="eda.html"><a href="eda.html#contexto-de-los-datos-de-walmart"><i class="fa fa-check"></i><b>3.4.1</b> Contexto de los datos de Walmart</a></li>
<li class="chapter" data-level="3.4.2" data-path="07-rls.html"><a href="#extracci%C3%B3n-transformaci%C3%B3n-y-carga-etl"><i class="fa fa-check"></i><b>3.4.2</b> Extracción, transformación y carga (ETL)</a></li>
<li class="chapter" data-level="3.4.3" data-path="07-rls.html"><a href="#an%C3%A1lisis-de-la-variable-weekly_sales-target"><i class="fa fa-check"></i><b>3.4.3</b> Análisis de la variable <code>weekly_sales</code> (Target)</a></li>
<li class="chapter" data-level="3.4.4" data-path="07-rls.html"><a href="#an%C3%A1lisis-de-las-variables-caracter%C3%ADsticas-independientes"><i class="fa fa-check"></i><b>3.4.4</b> Análisis de las variables características (independientes)</a></li>
<li class="chapter" data-level="3.4.5" data-path="07-rls.html"><a href="#an%C3%A1lisis-exploratorio-bivariado"><i class="fa fa-check"></i><b>3.4.5</b> Análisis exploratorio bivariado</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="07-rls.html"><a href="#an%C3%A1lisis-explotario-con-variable-respuesta-categ%C3%B3rica"><i class="fa fa-check"></i><b>3.5</b> Análisis explotario con variable respuesta categórica</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="eda.html"><a href="eda.html#contexto-del-conjunto-de-datos-de-marketing-de-un-banco"><i class="fa fa-check"></i><b>3.5.1</b> Contexto del conjunto de datos de marketing de un banco</a></li>
<li class="chapter" data-level="3.5.2" data-path="07-rls.html"><a href="#extracci%C3%B3n-transformaci%C3%B3n-y-carga-etl-1"><i class="fa fa-check"></i><b>3.5.2</b> Extracción, transformación y carga (ETL)</a></li>
<li class="chapter" data-level="3.5.3" data-path="07-rls.html"><a href="#an%C3%A1lisis-de-la-variable-y-target"><i class="fa fa-check"></i><b>3.5.3</b> Análisis de la variable <code>y</code> (Target)</a></li>
<li class="chapter" data-level="3.5.4" data-path="07-rls.html"><a href="#an%C3%A1lisis-de-las-variables-caracter%C3%ADsticas-independientes-1"><i class="fa fa-check"></i><b>3.5.4</b> Análisis de las variables características (independientes)</a></li>
<li class="chapter" data-level="3.5.5" data-path="07-rls.html"><a href="#an%C3%A1lisis-exploratorio-bivariado-1"><i class="fa fa-check"></i><b>3.5.5</b> Análisis exploratorio bivariado</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="estparynopar.html"><a href="estparynopar.html"><i class="fa fa-check"></i><b>4</b> Análisis de estadística paramétrica y no paramétrica</a>
<ul>
<li class="chapter" data-level="4.1" data-path="07-rls.html"><a href="#comparaci%C3%B3n-de-medias-entre-dos-grupos-independientes-con-estad%C3%ADstica-param%C3%A9trica"><i class="fa fa-check"></i><b>4.1</b> Comparación de medias entre dos grupos independientes con estadística paramétrica</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="estparynopar.html"><a href="estparynopar.html#condiciones-del-t-test-para-muestras-independientes"><i class="fa fa-check"></i><b>4.1.1</b> Condiciones del t-test para muestras independientes</a></li>
<li class="chapter" data-level="4.1.2" data-path="estparynopar.html"><a href="estparynopar.html#grados-de-libertad"><i class="fa fa-check"></i><b>4.1.2</b> Grados de libertad</a></li>
<li class="chapter" data-level="4.1.3" data-path="07-rls.html"><a href="#error-est%C3%A1ndar-de-la-diferencia-de-medias"><i class="fa fa-check"></i><b>4.1.3</b> Error estándar de la diferencia de medias</a></li>
<li class="chapter" data-level="4.1.4" data-path="07-rls.html"><a href="#tama%C3%B1o-del-efecto-effect-size-en-comparaciones-de-medias"><i class="fa fa-check"></i><b>4.1.4</b> Tamaño del Efecto (Effect Size) en comparaciones de medias</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="07-rls.html"><a href="#comparaci%C3%B3n-de-medias-entre-dos-grupos-pareados-con-estad%C3%ADstica-param%C3%A9trica"><i class="fa fa-check"></i><b>4.2</b> Comparación de medias entre dos grupos pareados con estadística paramétrica</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="estparynopar.html"><a href="estparynopar.html#supuestos-del-t-test-para-muestras-dependientes"><i class="fa fa-check"></i><b>4.2.1</b> Supuestos del t-test para muestras dependientes</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="07-rls.html"><a href="#comparaci%C3%B3n-de-dos-grupos-independientes-con-estad%C3%ADstica-no-param%C3%A9trica"><i class="fa fa-check"></i><b>4.3</b> Comparación de dos grupos independientes con estadística no paramétrica</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="estparynopar.html"><a href="estparynopar.html#fundamento-conceptual"><i class="fa fa-check"></i><b>4.3.1</b> Fundamento conceptual</a></li>
<li class="chapter" data-level="4.3.2" data-path="07-rls.html"><a href="#comparaci%C3%B3n-con-el-test-t"><i class="fa fa-check"></i><b>4.3.2</b> Comparación con el test t</a></li>
<li class="chapter" data-level="4.3.3" data-path="07-rls.html"><a href="#supuestos-y-condiciones-de-aplicaci%C3%B3n"><i class="fa fa-check"></i><b>4.3.3</b> Supuestos y condiciones de aplicación</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="07-rls.html"><a href="#comparaci%C3%B3n-de-dos-grupos-pareados-con-estad%C3%ADstica-no-param%C3%A9trica"><i class="fa fa-check"></i><b>4.4</b> Comparación de dos grupos pareados con estadística no paramétrica</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="07-rls.html"><a href="#cu%C3%A1ndo-se-recomienda-utilizar-esta-prueba"><i class="fa fa-check"></i><b>4.4.1</b> ¿Cuándo se recomienda utilizar esta prueba?</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="07-rls.html"><a href="#anova-an%C3%A1lisis-de-varianza-para-comparar-m%C3%BAltiples-medias"><i class="fa fa-check"></i><b>4.5</b> ANOVA (análisis de varianza para comparar múltiples medias)</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="07-rls.html"><a href="#supuestos-y-formulaci%C3%B3n-de-las-hip%C3%B3tesis"><i class="fa fa-check"></i><b>4.5.1</b> Supuestos y formulación de las hipótesis</a></li>
<li class="chapter" data-level="4.5.2" data-path="07-rls.html"><a href="#sumas-de-cuadrados-y-teorema-de-descomposici%C3%B3n"><i class="fa fa-check"></i><b>4.5.2</b> Sumas de cuadrados y teorema de descomposición</a></li>
<li class="chapter" data-level="4.5.3" data-path="estparynopar.html"><a href="estparynopar.html#estimaciones-insesgadas-de-la-varianza-poblacional"><i class="fa fa-check"></i><b>4.5.3</b> Estimaciones insesgadas de la varianza poblacional</a></li>
<li class="chapter" data-level="4.5.4" data-path="07-rls.html"><a href="#teorema-de-contraste-para-el-an%C3%A1lisis-de-varianza"><i class="fa fa-check"></i><b>4.5.4</b> Teorema de contraste para el análisis de varianza</a></li>
<li class="chapter" data-level="4.5.5" data-path="07-rls.html"><a href="#comparaciones-m%C3%BAltiples"><i class="fa fa-check"></i><b>4.5.5</b> Comparaciones múltiples</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="estparynopar.html"><a href="estparynopar.html#kruskalwallis"><i class="fa fa-check"></i><b>4.6</b> Kruskal–Wallis</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="07-rls.html"><a href="#hip%C3%B3tesis-del-test"><i class="fa fa-check"></i><b>4.6.1</b> Hipótesis del test</a></li>
<li class="chapter" data-level="4.6.2" data-path="07-rls.html"><a href="#estad%C3%ADstico-de-prueba"><i class="fa fa-check"></i><b>4.6.2</b> Estadístico de prueba</a></li>
<li class="chapter" data-level="4.6.3" data-path="estparynopar.html"><a href="estparynopar.html#condiciones-del-test-de-kruskalwallis"><i class="fa fa-check"></i><b>4.6.3</b> Condiciones del test de Kruskal–Wallis</a></li>
<li class="chapter" data-level="4.6.4" data-path="estparynopar.html"><a href="estparynopar.html#comparaciones-post-hoc"><i class="fa fa-check"></i><b>4.6.4</b> Comparaciones Post-Hoc</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="tabcontingencia.html"><a href="tabcontingencia.html"><i class="fa fa-check"></i><b>5</b> Tabla de contingencia</a>
<ul>
<li class="chapter" data-level="5.1" data-path="07-rls.html"><a href="#tablas-de-contingencia-con-dos-criterios-de-clasificaci%C3%B3n"><i class="fa fa-check"></i><b>5.1</b> Tablas de contingencia con dos criterios de clasificación</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="tabcontingencia.html"><a href="tabcontingencia.html#prueba-de-homogeneidad"><i class="fa fa-check"></i><b>5.1.1</b> Prueba de homogeneidad</a></li>
<li class="chapter" data-level="5.1.2" data-path="tabcontingencia.html"><a href="tabcontingencia.html#prueba-de-independencia"><i class="fa fa-check"></i><b>5.1.2</b> Prueba de independencia</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="correglin.html"><a href="correglin.html"><i class="fa fa-check"></i><b>6</b> Correlación lineal</a>
<ul>
<li class="chapter" data-level="6.1" data-path="07-rls.html"><a href="#definiciones-y-teorema-de-correlaci%C3%B3n"><i class="fa fa-check"></i><b>6.1</b> Definiciones y teorema de correlación</a></li>
<li class="chapter" data-level="6.2" data-path="07-rls.html"><a href="#an%C3%A1lisis-de-correlaci%C3%B3n-simple-dos-variables"><i class="fa fa-check"></i><b>6.2</b> Análisis de correlación simple (dos variables)</a>
<ul>
<li class="chapter" data-level="6.2.1" data-path="07-rls.html"><a href="#tipos-de-coeficientes-de-correlaci%C3%B3n"><i class="fa fa-check"></i><b>6.2.1</b> Tipos de coeficientes de correlación</a></li>
<li class="chapter" data-level="6.2.2" data-path="07-rls.html"><a href="#interpretaci%C3%B3n-del-coeficiente-de-correlaci%C3%B3n"><i class="fa fa-check"></i><b>6.2.2</b> Interpretación del coeficiente de correlación</a></li>
<li class="chapter" data-level="6.2.3" data-path="07-rls.html"><a href="#correlaci%C3%B3n-de-pearson"><i class="fa fa-check"></i><b>6.2.3</b> Correlación de Pearson</a></li>
<li class="chapter" data-level="6.2.4" data-path="07-rls.html"><a href="#correlaci%C3%B3n-de-spearman"><i class="fa fa-check"></i><b>6.2.4</b> Correlación de Spearman</a></li>
<li class="chapter" data-level="6.2.5" data-path="07-rls.html"><a href="#correlaci%C3%B3n-de-kendall"><i class="fa fa-check"></i><b>6.2.5</b> Correlación de Kendall</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="rls.html"><a href="rls.html"><i class="fa fa-check"></i><b>7</b> Regresión lineal simple</a>
<ul>
<li class="chapter" data-level="7.1" data-path="07-rls.html"><a href="#el-modelo-de-regresi%C3%B3n-lineal-simple-rls"><i class="fa fa-check"></i><b>7.1</b> El modelo de regresión lineal simple (RLS)</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="07-rls.html"><a href="#modelo-determinista-y-modelo-probabil%C3%ADstico"><i class="fa fa-check"></i><b>7.1.1</b> Modelo determinista y modelo probabilístico</a></li>
<li class="chapter" data-level="7.1.2" data-path="07-rls.html"><a href="#supuestos-b%C3%A1sicos-para-el-modelo-de-regresi%C3%B3n-lineal."><i class="fa fa-check"></i><b>7.1.2</b> Supuestos básicos para el modelo de regresión lineal.</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="07-rls.html"><a href="#estimaci%C3%B3n-de-los-par%C3%A1metros-por-minimos-cuadrados-de-beta_0-beta_1"><i class="fa fa-check"></i><b>7.2</b> Estimación de los parámetros por minimos cuadrados de <span class="math inline">\(\beta_0, \beta_1\)</span></a></li>
<li class="chapter" data-level="7.3" data-path="07-rls.html"><a href="#estimaci%C3%B3n-de-sigma2"><i class="fa fa-check"></i><b>7.3</b> Estimación de <span class="math inline">\(\sigma^2\)</span></a></li>
</ul></li>
<li class="chapter" data-level="" data-path="referencias-1.html"><a href="referencias-1.html"><i class="fa fa-check"></i>Referencias</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Publicado con bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Notas de métodos estadísticos</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="rls" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Capítulo 7</span> Regresión lineal simple<a href="rls.html#rls" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>En muchos procesos productivos se controlan las condiciones de operación de un sistema. Es fundamental determinar cómo una <strong>variable respuesta</strong> cambia dependiendo de dichas condiciones.</p>
<p>Por ejemplo, en un proceso de <strong>embutido de cárnicos</strong>, la <strong>cantidad de producto empacado (en gramos)</strong> puede depender de la <strong>velocidad</strong> y la <strong>temperatura</strong> de operación de una máquina.</p>
<p>En la practica, por supuesto es importante</p>
<ol style="list-style-type: decimal">
<li><strong>Entender la relación</strong> entre la cantidad de producto empacado, la velocidad y la temperatura de operación.<br />
</li>
<li><strong>Garantizar el cumplimiento</strong> de las especificaciones en la cantidad de producto empacado.<br />
</li>
<li><strong>Optmizar las condiciones de operación</strong> para reducir costos y minimizar desperdicios.</li>
</ol>
<p>El <strong>Modelo de Regresión Lineal</strong> se aplica ampliamente en ingeniería cuando se busca dar respuesta a los tres puntos anteriores.</p>
<p>En general, los modelos de regresión lineal permiten estudiar la relación entre:</p>
<ul>
<li>Una <strong>variable respuesta</strong> <span class="math inline">\(Y\)</span>.<br />
</li>
<li>Un conjunto de <strong>variables controlables</strong> del proceso, denotadas como <span class="math inline">\(X_1, X_2, \dots, X_k\)</span>.</li>
</ul>
<p>Una vez entendida esta relación, es posible <strong>predecir valores futuros</strong> de la variable respuesta a partir de valores <strong>específicos y conocidos</strong> de las variables controlables.</p>
<div class="admon-box nota">
<div class="admon-title">
<span class="icon"></span> Nota: variable controlable
</div>
<p>
<strong>Variable controlable</strong>: Son aquellas variables de proceso que pueden medirse fácilmente y mantenerse <strong>fijas</strong> durante la operación.
</p>
</div>
<p>Dependiendo del número de variables controlables, distinguimos:</p>
<ol style="list-style-type: decimal">
<li><p><strong>Modelo de Regresión Lineal Simple (RLS):</strong><br />
Cuando se tiene <strong>una sola variable controlable</strong>, digamos <span class="math inline">\(x\)</span>.</p></li>
<li><p><strong>Modelo de Regresión Lineal Múltiple (RLM):</strong><br />
Cuando existen <strong>más de una variable controlable</strong>, digamos <span class="math inline">\(x_1, x_2, \dots, x_k\)</span>.</p>
<ul>
<li>Ejemplo en procesos de embutidos:<br />
<span class="math display">\[
x_1 = \text{velocidad}, \quad x_2 = \text{temperatura}
\]</span></li>
</ul></li>
</ol>
<div id="el-modelo-de-regresión-lineal-simple-rls" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> El modelo de regresión lineal simple (RLS)<a href="#el-modelo-de-regresi%C3%B3n-lineal-simple-rls" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ul>
<li>Consideremos un proceso donde se tienen registros de la <code>Resistencia</code>, en <code>psi</code>, y la <code>Edad</code>, en semanas, de varias soldaduras. Los datos pueden leerse en <strong>R</strong> como se muestra a continuación:</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="rls.html#cb1-1" tabindex="-1"></a><span class="do">## Lectura de datos desde archivo local</span></span>
<span id="cb1-2"><a href="rls.html#cb1-2" tabindex="-1"></a>file <span class="ot">&lt;-</span> <span class="st">&quot;data/data_rls.txt&quot;</span></span>
<span id="cb1-3"><a href="rls.html#cb1-3" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.table</span>(file, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-4"><a href="rls.html#cb1-4" tabindex="-1"></a></span>
<span id="cb1-5"><a href="rls.html#cb1-5" tabindex="-1"></a><span class="do">## Primeras 6 filas</span></span>
<span id="cb1-6"><a href="rls.html#cb1-6" tabindex="-1"></a><span class="fu">head</span>(df)</span></code></pre></div>
</details>
<pre><code>##   Resistencia Edad
## 1        10.9 18.7
## 2        10.6 19.1
## 3        13.4  9.3
## 4        10.7 17.5
## 5        13.0 14.6
## 6        13.1 12.8</code></pre>
<ul>
<li>Con miras explorar si existe una relación entre la <code>Resistencia</code> y la <code>Edad</code> de la soldadura, existen dos estrategias.</li>
</ul>
<div class="admon-box observacion">
<div class="admon-title">
<span class="icon"></span> observación
</div>
En RLS, es posible establecer si existe una posible relación entre <span class="math inline">\(X\)</span> y <span class="math inline">\(Y\)</span> es
<ol>
<li>
Construir un gráfico de dispersión
</li>
<li>
Calculando el coeficiente de correlación lineal muestral
</li>
</ol>
</div>
<ul>
<li>Para construir un gráfico de dispersión procedemos de la siguiente manera:</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="rls.html#cb3-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb3-2"><a href="rls.html#cb3-2" tabindex="-1"></a></span>
<span id="cb3-3"><a href="rls.html#cb3-3" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb3-4"><a href="rls.html#cb3-4" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Edad, <span class="at">y =</span> Resistencia)) <span class="sc">+</span> </span>
<span id="cb3-5"><a href="rls.html#cb3-5" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb3-6"><a href="rls.html#cb3-6" tabindex="-1"></a>  <span class="fu">theme_bw</span>()</span></code></pre></div>
</details>
<p><img src="bookdown-demo_files/figure-html/dis_rls-1.png" width="672" /></p>
<ul>
<li><p>Observe que, aparentemente, cuanto mayor sea la <code>Edad</code> de la soldadura menor será su <code>Resistencia</code>. Por lo tanto, podemos decir que la relación entre <code>Edad</code> y <code>Resistencia</code> es <strong>inversamente proporcional</strong>.</p></li>
<li><p>Ahora, miremos la correlación, suponiendo que los datos tienen comportamiento</p></li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="rls.html#cb4-1" tabindex="-1"></a><span class="do">## coeficiente de correlación</span></span>
<span id="cb4-2"><a href="rls.html#cb4-2" tabindex="-1"></a><span class="fu">with</span>(df, <span class="fu">cor</span>(Edad, Resistencia))</span></code></pre></div>
</details>
<pre><code>## [1] -0.8827718</code></pre>
<ul>
<li>Por lo tanto, concluimos que la relación entre la <code>Edad</code> de la soldadura y su <code>Resistencia</code> es inversamente proporcional.</li>
</ul>
<div id="modelo-determinista-y-modelo-probabilístico" class="section level3 hasAnchor" number="7.1.1">
<h3><span class="header-section-number">7.1.1</span> Modelo determinista y modelo probabilístico<a href="#modelo-determinista-y-modelo-probabil%C3%ADstico" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Para el modelo determinista:</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_i,
\]</span></p>
<p>el valor observado de la <strong>Resistencia</strong> <span class="math inline">\(Y_i\)</span> es una función lineal de la <strong>Edad</strong> <span class="math inline">\(x_i\)</span>.</p>
<p>La generalización apropiada de esto a un modelo probabilístico supone que el <strong>valor esperado</strong> de la Resistencia <span class="math inline">\(Y_i\)</span> es una <strong>función lineal</strong> de la Edad <span class="math inline">\(x_i\)</span>. Si denotamos por <span class="math inline">\(E(Y_i \,|\, X = x_i)\)</span> a la esperanza de la variable aleatoria <span class="math inline">\(Y_i\)</span>, entonces bajo el supuesto de linealidad podemos escribir:</p>
<p><span class="math display">\[
E(Y_i \,|\, X = x_i) \;=\; \beta_0 + \beta_1 x_i. \tag{7.1}
\]</span></p>
<p>En la práctica, el valor observado de <span class="math inline">\(Y_i\)</span> (Resistencia medida) se desviará inevitablemente de su valor esperado debido a la variabilidad y errores de medición.</p>
<p>Si esta diferencia se representa mediante la variable aleatoria <span class="math inline">\(\varepsilon_i\)</span>, con media cero por (7.1), se puede establecer:</p>
<p><span class="math display">\[
\varepsilon_i \;=\; Y_i - E(Y_i \,|\, X = x_i) \;=\; Y_i - (\beta_0 + \beta_1 x_i),
\]</span></p>
<p>o de manera equivalente:</p>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1 x_i + \varepsilon_i. \tag{7.2}
\]</span></p>
<p>La ecuación (7.2) es la llamada <strong>recta verdadera (o poblacional) de regresión</strong>, que describe la relación entre la <strong>Resistencia (psi)</strong> y la <strong>Edad (semanas)</strong> de las soldaduras, considerando tanto la tendencia promedio como la variabilidad aleatoria.</p>
<div class="admon-box definicion">
<div class="admon-title">
<span class="icon"></span> Definición
</div>
<p>
<p>Supongamos que estamos interesados en conocer la relación entre la variable <span class="math inline">\(Y\)</span> y una independente <span class="math inline">\(X\)</span>. Si la variable <span class="math inline">\(X\)</span> toma los valores <span class="math inline">\(x_i\)</span>, entonces la ecuación de la <strong>recta poblacional de regresión</strong> expresa los correspondientes valores de <span class="math inline">\(Y_i\)</span> como:</p>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1 x_i + \varepsilon_i,
\]</span></p>
donde <span class="math inline">\(\beta_0\)</span> y <span class="math inline">\(\beta_1\)</span> son constantes, y <span class="math inline">\(\varepsilon_i\)</span>, llamado <strong>término de error</strong>, es una variable aleatoria con media cero.
</p>
</div>
</div>
<div id="supuestos-básicos-para-el-modelo-de-regresión-lineal." class="section level3 hasAnchor" number="7.1.2">
<h3><span class="header-section-number">7.1.2</span> Supuestos básicos para el modelo de regresión lineal.<a href="#supuestos-b%C3%A1sicos-para-el-modelo-de-regresi%C3%B3n-lineal." class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Los supuestos para el modelo de regresión lineal son</p>
<div class="admon-box advertencia">
<div class="admon-title">
<span class="icon"></span> Supuestos para el modelo de regresión lineal simple
</div>
<p>
Denotemos la recta verdadera de regresión por
<span class="math inline">\(Y_i = \beta_0 + \beta_1 x_i + \varepsilon_i\)</span> y asumamos que se dispone de
<span class="math inline">\(n\)</span> pares de observaciones. Suelen realizarse, al respecto, los siguientes supuestos:
</p>
<ol>
<li>
Cada <span class="math inline">\(x_i\)</span> es un número fijo (asignado, por ejemplo, por un investigador)
o es la realización de una variable aleatoria <span class="math inline">\(X_i\)</span> independiente del término de error
<span class="math inline">\(\varepsilon_i\)</span>. En el último caso, la inferencia se realiza condicionando al valor observado <span class="math inline">\(x_i\)</span>.
</li>
<li>
Los términos de error <span class="math inline">\(\varepsilon_i\)</span> son variables aleatorias con media 0,
es decir, <span class="math inline">\(E(\varepsilon_i) = 0\)</span>, para todo <span class="math inline">\(i = 1, \ldots, n\)</span>.
</li>
<li>
Las variables aleatorias <span class="math inline">\(\varepsilon_i\)</span> tienen todas la misma varianza <span class="math inline">\(\sigma^2\)</span>,
es decir, <span class="math inline">\(V(\varepsilon_i) = \sigma^2\)</span>, para todo <span class="math inline">\(i = 1, \ldots, n\)</span>.
</li>
<li>
Las variables aleatorias <span class="math inline">\(\varepsilon_i\)</span> no se hallan correlacionadas, es decir, son independientes,
luego <span class="math inline">\(E(\varepsilon_i \varepsilon_j) = 0\)</span>, para todo <span class="math inline">\(i, j = 1, \ldots, n\)</span>, con <span class="math inline">\(i \neq j\)</span>.
</li>
<li>
Los errores <span class="math inline">\(\varepsilon_i\)</span> estan distribuidos normalmente.
</li>
</ol>
</div>
<div class="admon-box teorema">
<div class="admon-title">
<span class="icon"></span> Teorema
</div>
<p>
Denotando la recta verdadera de regresión por
<span class="math inline">\(Y_i = \beta_0 + \beta_1 x_i + \varepsilon_i\)</span>,
si se cumplen los supuestos del modelo de regresión, entonces, para un valor fijo <span class="math inline">\(x_i\)</span> de <span class="math inline">\(X\)</span>,
la esperanza y varianza condicionales de <span class="math inline">\(Y_i\)</span>, dado que <span class="math inline">\(X = x_i\)</span>, vienen dadas, respectivamente, por:
</p>
<p style="text-align:center;">
<span class="math inline">\(E(Y_i \,|\, X = x_i) = \beta_0 + \beta_1 x_i \quad \text{y} \quad V(Y_i \,|\, X = x_i) = \sigma^2.\)</span>
</p>
</div>
<p style="text-align: left;">
<strong>Demostración del teorema</strong>
</p>
<ol>
<li>
<strong>Esperanza condicional.</strong><br/>
Usando linealidad de la esperanza y que <span class="math inline">\(\beta_0\)</span> y <span class="math inline">\(\beta_1\, x_i\)</span> son constantes dado <span class="math inline">\(X=x_i\)</span>:
<span class="math display">\[
      E(Y_i \mid X=x_i)
      = E(\beta_0 + \beta_1 x_i + \varepsilon_i \mid X=x_i)
      = \beta_0 + \beta_1 x_i + E(\varepsilon_i \mid X=x_i).
      \]</span>
Por independencia (o, en su defecto, por el supuesto <span class="math inline">\(E(\varepsilon_i\mid X)=0\)</span>):
<span class="math display">\[
      E(\varepsilon_i \mid X=x_i)=0.
      \]</span>
Luego,
<span class="math display">\[
      \boxed{\,E(Y_i \mid X=x_i)=\beta_0+\beta_1 x_i\,}.
      \]</span>
</li>
<li>
<p><strong>Varianza condicional.</strong><br/>
La varianza de una constante es cero y <span class="math inline">\(\beta_0+\beta_1 x_i\)</span> es constante dado <span class="math inline">\(X=x_i\)</span>:</p>
<p><span class="math display">\[\begin{align}
\operatorname{Var}(Y_i \mid X=x_i)
  &amp;= \operatorname{Var}(\beta_0 + \beta_1 x_i + \varepsilon_i \mid X=x_i) \\[6pt]
  &amp;= \operatorname{Var}(\beta_0 + \beta_1 x_i \mid X=x_i)
     + \operatorname{Var}(\varepsilon_i \mid X=x_i) \\[6pt]
  &amp;= 0 + \operatorname{Var}(\varepsilon_i \mid X=x_i).
\end{align}\]</span></p>
Por independencia (o por homocedasticidad condicional):
<span class="math display">\[
      \operatorname{Var}(\varepsilon_i \mid X=x_i) = \operatorname{Var}(\varepsilon_i)=\sigma^2.
      \]</span>
Por tanto,
<span class="math display">\[
      \boxed{\,\operatorname{Var}(Y_i \mid X=x_i)=\sigma^2\,}.
      \]</span>
</li>
</ol>
<p>En general, el modelo de RLS surge ante la necesidad de predecir una variable respuesta <span class="math inline">\(Y\)</span>, generalmente continua, como función de una variable controlable <span class="math inline">\(X\)</span>, donde matematicamente el modelo puede expresarse como:</p>
<p><span class="math display">\[
Y_i = \beta_0 + \beta_1 X_i + \varepsilon_i,
\]</span>
<span class="math display">\[
\varepsilon_i \sim \mathcal{N}(0,\sigma^2),
\]</span>
<span class="math display">\[
\sigma^2 = \text{constante}.
\]</span></p>
<p>donde <span class="math inline">\((\beta_0, \beta_1, \sigma^2)\)</span> corresponden a los <strong>parámetros del modelo</strong> y <span class="math inline">\(\varepsilon_i\)</span> es el error aleatorio para la observación <span class="math inline">\(i\)</span>.</p>
<ul>
<li>Los términos <span class="math inline">\((\beta_0, \beta_1)\)</span> se conocen como los <strong>coeficientes del modelo</strong>.<br />
</li>
<li><span class="math inline">\(\sigma^2\)</span> corresponde a la <strong>varianza</strong> de los errores.</li>
</ul>
<p>En la práctica, se tiene o se toma una <strong>muestra aleatoria de tamaño <span class="math inline">\(n\)</span></strong> proveniente de una población o de un proceso de producción/servicios.<br />
A partir de dicha muestra, se busca estimar los valores de <span class="math inline">\((\beta_0, \beta_1, \sigma^2)\)</span>.</p>
</div>
</div>
<div id="estimación-de-los-parámetros-por-minimos-cuadrados-de-beta_0-beta_1" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Estimación de los parámetros por minimos cuadrados de <span class="math inline">\(\beta_0, \beta_1\)</span><a href="#estimaci%C3%B3n-de-los-par%C3%A1metros-por-minimos-cuadrados-de-beta_0-beta_1" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Para estimar <span class="math inline">\(\beta_0\)</span> y <span class="math inline">\(\beta_1\)</span> se usa el <strong>método de mínimos cuadrados</strong>. Esto es, se estiman <span class="math inline">\(\beta_0\)</span> y <span class="math inline">\(\beta_1\)</span> tales que la suma de los cuadrados de las diferencias entre las observaciones <span class="math inline">\(y_i\)</span> y la línea recta sea mínima.</p>
<p>El modelo es:</p>
<p><span class="math display">\[
y_i = \beta_0 + \beta_1 x_i + \varepsilon_i, \quad i=1,2,\ldots,n
\]</span></p>
<p>El criterio de mínimos cuadrados es:</p>
<p><span class="math display">\[
S(\beta_0,\beta_1) = \sum_{i=1}^n \varepsilon_i^2=\sum_{i=1}^n (y_i - \beta_0 - \beta_1 x_i)^2
\]</span></p>
<p>Para obtener los estimadores, derivamos respecto a <span class="math inline">\(\beta_0\)</span> y <span class="math inline">\(\beta_1\)</span>:</p>
<p><span class="math display">\[\begin{align}
\frac{\partial S}{\partial \beta_0}\Big|_{\hat{\beta}_0,\hat{\beta}_1}
&amp;= -2 \sum_{i=1}^n (y_i - \hat{\beta}_0 - \hat{\beta}_1 x_i) = 0 \\[6pt]
\frac{\partial S}{\partial \beta_1}\Big|_{\hat{\beta}_0,\hat{\beta}_1}
&amp;= -2 \sum_{i=1}^n (y_i - \hat{\beta}_0 - \hat{\beta}_1 x_i)x_i = 0
\end{align}\]</span></p>
<p>Estas se simplifican a las llamadas <strong>ecuaciones normales</strong>:</p>
<p><span class="math display">\[\begin{align}
n\hat{\beta}_0 + \hat{\beta}_1 \sum_{i=1}^n x_i &amp;= \sum_{i=1}^n y_i \\[6pt]
\hat{\beta}_0 \sum_{i=1}^n x_i + \hat{\beta}_1 \sum_{i=1}^n x_i^2 &amp;= \sum_{i=1}^n y_i x_i
\end{align}\]</span></p>
<p>La solución de este sistema es:</p>
<p><span class="math display">\[
\hat{\beta}_0 = \bar{y} - \hat{\beta}_1 \bar{x}
\]</span></p>
<p><span class="math display">\[
\hat{\beta}_1 = \frac{\sum_{i=1}^n y_i x_i - \frac{1}{n}\left(\sum_{i=1}^n y_i\right)\left(\sum_{i=1}^n x_i\right)}
{\sum_{i=1}^n x_i^2 - \frac{1}{n}\left(\sum_{i=1}^n x_i\right)^2}
\]</span></p>
<p>donde:</p>
<p><span class="math display">\[
\bar{y} = \frac{1}{n}\sum_{i=1}^n y_i,
\qquad
\bar{x} = \frac{1}{n}\sum_{i=1}^n x_i
\]</span></p>
<p>El modelo ajustado es:</p>
<p><span class="math display">\[
\hat{y} = \hat{\beta}_0 + \hat{\beta}_1 x
\]</span></p>
<p>De manera más sencilla, definimos:</p>
<p><span class="math display">\[
S_{xx} = \sum_{i=1}^n (x_i - \bar{x})^2
\qquad \text{y} \qquad
S_{xy} = \sum_{i=1}^n (x_i - \bar{x})(y_i - \bar{y})
\]</span></p>
<p>Entonces, una forma conveniente de escribir la pendiente es:</p>
<p><span class="math display">\[
\hat{\beta}_1 = \frac{S_{xy}}{S_{xx}}
\]</span></p>
<div class="admon-box ejercicio">
<div class="admon-title">
<span class="icon"></span> Ejercicio
</div>
<p>
Queda de ejercicio verificar que en dicho punto crítico se alcanza un mínimo local. Sugerencia, realizar la segundas derivadas parciales.
</p>
</div>
<div class="admon-box ejercicio">
<div class="admon-title">
<span class="icon"></span> Ejercicio
</div>
<p>
<ol>
<li>
Demuestre que
<span class="math display">\[\sum_{i=1}^n (x_i - \overline{x})(y_i - \overline{y}) = \sum_{i=1}^n x_i y_i - n \, \overline{x} \, \overline{y}\]</span>
</li>
<li>
Demuestre que
<span class="math display">\[\sum_{i=1}^n (x_i - \overline{x})^2 = \sum_{i=1}^n x_i^2 - n \overline{x}^2\]</span>
</li>
</ol>
</p>
</div>
<div class="admon-box observacion">
<div class="admon-title">
<span class="icon"></span> Observacion
</div>
<p>
En la práctica, <span class="math inline">\(\hat{\beta}_1\)</span> se interpreta como <strong>el cambio unitario</strong> en el valor esperado de <span class="math inline">\(Y\)</span>, es decir, en <span class="math inline">\(E[Y\mid X]\)</span>, por cada cambio unitario del <strong>factor controlable</strong> <span class="math inline">\(X\)</span>.
</p>
</div>
<ul>
<li>Continuando con el ejemplo de los datos de soldadura, estimemos paso a paso <span class="math inline">\(\beta_0, \beta_1\)</span>:</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="rls.html#cb6-1" tabindex="-1"></a><span class="co"># 1. Lectura de datos</span></span>
<span id="cb6-2"><a href="rls.html#cb6-2" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.table</span>(file, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb6-3"><a href="rls.html#cb6-3" tabindex="-1"></a></span>
<span id="cb6-4"><a href="rls.html#cb6-4" tabindex="-1"></a><span class="co"># 2. Variables</span></span>
<span id="cb6-5"><a href="rls.html#cb6-5" tabindex="-1"></a>Y <span class="ot">&lt;-</span> df<span class="sc">$</span>Resistencia</span>
<span id="cb6-6"><a href="rls.html#cb6-6" tabindex="-1"></a>X <span class="ot">&lt;-</span> df<span class="sc">$</span>Edad</span>
<span id="cb6-7"><a href="rls.html#cb6-7" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(X)</span>
<span id="cb6-8"><a href="rls.html#cb6-8" tabindex="-1"></a></span>
<span id="cb6-9"><a href="rls.html#cb6-9" tabindex="-1"></a><span class="co"># 3. Medias</span></span>
<span id="cb6-10"><a href="rls.html#cb6-10" tabindex="-1"></a>x_bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(X)</span>
<span id="cb6-11"><a href="rls.html#cb6-11" tabindex="-1"></a>y_bar <span class="ot">&lt;-</span> <span class="fu">mean</span>(Y)</span>
<span id="cb6-12"><a href="rls.html#cb6-12" tabindex="-1"></a></span>
<span id="cb6-13"><a href="rls.html#cb6-13" tabindex="-1"></a><span class="co"># 4. Cálculo de Sxx y Sxy</span></span>
<span id="cb6-14"><a href="rls.html#cb6-14" tabindex="-1"></a>Sxx <span class="ot">&lt;-</span> <span class="fu">sum</span>((X <span class="sc">-</span> x_bar)<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb6-15"><a href="rls.html#cb6-15" tabindex="-1"></a>Sxy <span class="ot">&lt;-</span> <span class="fu">sum</span>((X <span class="sc">-</span> x_bar) <span class="sc">*</span> (Y <span class="sc">-</span> y_bar))</span>
<span id="cb6-16"><a href="rls.html#cb6-16" tabindex="-1"></a></span>
<span id="cb6-17"><a href="rls.html#cb6-17" tabindex="-1"></a><span class="co"># 5. Estimadores de mínimos cuadrados</span></span>
<span id="cb6-18"><a href="rls.html#cb6-18" tabindex="-1"></a>beta1 <span class="ot">&lt;-</span> Sxy <span class="sc">/</span> Sxx</span>
<span id="cb6-19"><a href="rls.html#cb6-19" tabindex="-1"></a>beta1</span></code></pre></div>
</details>
<pre><code>## [1] -0.2437636</code></pre>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="rls.html#cb8-1" tabindex="-1"></a>beta0 <span class="ot">&lt;-</span> y_bar <span class="sc">-</span> beta1 <span class="sc">*</span> x_bar</span>
<span id="cb8-2"><a href="rls.html#cb8-2" tabindex="-1"></a>beta0</span></code></pre></div>
</details>
<pre><code>## [1] 15.74275</code></pre>
<p>En <strong>R</strong> la función clave paara ajustar modelos de RLS es <code>lm</code>. Para mayor información, puede consultar la ayuda de la función escribiendo <code>?lm</code> en la consola, o en la <a href="https://stat.ethz.ch/R-manual/R-devel/library/stats/html/lm.html">página oficial</a>.</p>
<p>En general, la sintaxis es</p>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="rls.html#cb10-1" tabindex="-1"></a><span class="co"># ajuste del modelo de RLS</span></span>
<span id="cb10-2"><a href="rls.html#cb10-2" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(Resistencia <span class="sc">~</span> Edad, <span class="at">data =</span> df)</span>
<span id="cb10-3"><a href="rls.html#cb10-3" tabindex="-1"></a>modelo</span></code></pre></div>
</details>
<pre><code>## 
## Call:
## lm(formula = Resistencia ~ Edad, data = df)
## 
## Coefficients:
## (Intercept)         Edad  
##     15.7427      -0.2438</code></pre>
<p>Los resultados indican que <span class="math inline">\(\hat{\beta}_0 = 15.74\)</span> y <span class="math inline">\(\hat{\beta}_1 = -0.244\)</span>. Por lo tanto, el modelo ajustado puede escribirse como:</p>
<p><span class="math display">\[
\widehat{\text{Resistencia}}_i = 15.74 \;-\; 0.244 \,\text{Edad}_i,
\]</span></p>
<p><span class="math display">\[
\varepsilon_i \sim N(0, \sigma^2),
\qquad
\sigma^2 = \text{constante}.
\]</span></p>
<div class="admon-box nota">
<div class="admon-title">
<span class="icon"></span> Interpretación de <span class="math inline">\(\,\hat{\beta}_0\,\)</span> y <span class="math inline">\(\,\hat{\beta}_1\)</span>
</div>
<ol>
<li>
Se espera que, por cada semana que transcurre, la <strong>resistencia de la soldadura</strong> disminuya <strong>0.244 psi</strong>. Es decir, <span class="math inline">\(\hat{\beta}_1 = -0.244\)</span>.
</li>
<li>
Una soldadura <strong>nueva</strong> <span class="math inline">\((\text{Edad} = 0)\)</span> tiene una resistencia promedio de <strong>15.74 psi</strong>. Es decir, <span class="math inline">\(\hat{\beta}_0 = 15.74\)</span>.
</li>
</ol>
</div>
<div class="admon-box ejercicio">
<div class="admon-title">
<span class="icon"></span> Ejercicio 1
</div>
<p>
Las cantidades de un compuesto químico “y”, que se disuelven en 100 gramos de agua a varias temperaturas “x”, se registran como sigue:
</p>
<table>
<thead>
<tr>
<th>
x (°C)
</th>
<th>
y (gramos)
</th>
</tr>
</thead>
<tbody>
<tr>
<td>
0
</td>
<td>
8
</td>
</tr>
<tr>
<td>
0
</td>
<td>
6
</td>
</tr>
<tr>
<td>
0
</td>
<td>
8
</td>
</tr>
<tr>
<td>
15
</td>
<td>
12
</td>
</tr>
<tr>
<td>
15
</td>
<td>
10
</td>
</tr>
<tr>
<td>
15
</td>
<td>
14
</td>
</tr>
<tr>
<td>
30
</td>
<td>
25
</td>
</tr>
<tr>
<td>
30
</td>
<td>
21
</td>
</tr>
<tr>
<td>
30
</td>
<td>
24
</td>
</tr>
<tr>
<td>
45
</td>
<td>
31
</td>
</tr>
<tr>
<td>
45
</td>
<td>
33
</td>
</tr>
<tr>
<td>
45
</td>
<td>
28
</td>
</tr>
<tr>
<td>
60
</td>
<td>
44
</td>
</tr>
<tr>
<td>
60
</td>
<td>
39
</td>
</tr>
<tr>
<td>
60
</td>
<td>
42
</td>
</tr>
<tr>
<td>
75
</td>
<td>
48
</td>
</tr>
<tr>
<td>
75
</td>
<td>
51
</td>
</tr>
<tr>
<td>
75
</td>
<td>
44
</td>
</tr>
</tbody>
</table>
<ol type="a">
<li>
Grafique un diagrama de dispersión de los datos. ¿Parecerá plausible un modelo de regresión lineal simple?
</li>
<li>
Encuentre las estimaciones de mínimos cuadrados de la pendiente y la ordenada al origen del modelo de regresión lineal simple.
</li>
<li>
Estime la cantidad de compuesto químico que se disolverá en 100 gramos de agua a 50°C.
</li>
</ol>
</div>
</div>
<div id="estimación-de-sigma2" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Estimación de <span class="math inline">\(\sigma^2\)</span><a href="#estimaci%C3%B3n-de-sigma2" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Además de estimar <span class="math inline">\(\beta_0\)</span> y <span class="math inline">\(\beta_1\)</span>, se requiere un estimado de <span class="math inline">\(\sigma^2\)</span> para probar hipótesis y formar intervalos de confianza pertinentes al modelo de regresión.</p>
<p>Ahora, se llama <strong>residuos</strong> (errores) a las desviaciones verticales</p>
<p><span class="math display">\[\varepsilon_i = y_i - \hat{y}_i, \quad i = 1, 2, \ldots, n\]</span></p>
<p>de la recta estimada.</p>
<p>Cuando no se puede usar información previa, el estimado de <span class="math inline">\(\sigma^2\)</span> se obtiene de la <strong>suma de cuadrados de los errores (SSE)</strong>:</p>
<p><span class="math display">\[
SSE = S = \sum_{i=1}^n \varepsilon_i^2 = \sum_{i=1}^n (y_i - \hat{y}_i)^2 \tag{7.3}
\]</span></p>
<p>Si sustituimos <span class="math inline">\(\hat{y}_i = \hat{\beta_0}+\hat{\beta_1}x_i\)</span> en la ecuación (7.3) tenemos que</p>
<p><span class="math display">\[\begin{align}
SSE &amp;= \sum_{i=1}^n (y_i - \hat{y}_i)^2 \\[6pt]
&amp;= \sum_{i=1}^n \left( y_i - \hat{\beta}_0 - \hat{\beta}_1 x_i \right)^2 \\[6pt]
&amp;= \sum_{i=1}^n \left( y_i - \bar{y} + \hat{\beta}_1 \bar{x} - \hat{\beta}_1 x_i \right)^2 \\[6pt]
&amp;= \sum_{i=1}^n \left[ (y_i - \bar{y}) - \hat{\beta}_1 (x_i - \bar{x}) \right]^2 \\[6pt]
&amp;= \sum_{i=1}^n (y_i - \bar{y})^2
   - 2\hat{\beta}_1 \sum_{i=1}^n (y_i - \bar{y})(x_i - \bar{x})
   + \hat{\beta}_1^2 \sum_{i=1}^n (x_i - \bar{x})^2 \\[6pt]
&amp;= SST - 2\hat{\beta}_1 S_{xy} + \hat{\beta}_1^2 S_{xx}
\end{align}\]</span></p>
<p>Como <span class="math inline">\(\hat{\beta_1}=\frac{S_{xy}}{S_{xx}}\)</span> se sigue que</p>
<p><span class="math display">\[\begin{align}
SSE &amp;= SST - 2\hat{\beta}_1 S_{xy} + \hat{\beta}_1^2 S_{xx} \\[6pt]
&amp;= SST - 2\hat{\beta}_1 S_{xy} + \hat{\beta}_1 \left(\frac{S_{xy}}{S_{xx}}\right) S_{xx} \\[6pt]
&amp;= SST - 2\hat{\beta}_1 S_{xy} + \hat{\beta}_1 S_{xy} \\[6pt]
&amp;= SST - \hat{\beta}_1 S_{xy}.
\end{align}\]</span></p>
<p>La suma de cuadrados de residuales tiene <span class="math inline">\(n - 2\)</span> grados de libertad, porque dos grados de libertad se asocian con los estimados <span class="math inline">\(\hat{\beta}_0\)</span> y <span class="math inline">\(\hat{\beta}_1\)</span> que se usan para obtener <span class="math inline">\(\hat{y}_i\)</span>.</p>
<p>Por el teorema de MSA y MSE insesgado de <span class="math inline">\(\sigma^2\)</span>, sabemos que el valor esperado de <span class="math inline">\(SSE\)</span> es:</p>
<p><span class="math display">\[
E(SSE) = (n-2)\sigma^2,
\]</span></p>
<p>por lo que un <strong>estimador insesgado</strong> de <span class="math inline">\(\sigma^2\)</span> es:</p>
<p><span class="math display">\[
\hat{\sigma}^2 = \frac{SSE}{n-2} = MSE
\]</span></p>
<p>La cantidad <span class="math inline">\(MSE\)</span> se llama <strong>cuadrado medio residual</strong>. La raíz cuadrada de <span class="math inline">\(\hat{\sigma}^2\)</span> se llama, a veces, el <strong>error estándar de la regresión (RSE)</strong>, y tiene las mismas unidades que la variable respuesta <span class="math inline">\(y\)</span>.</p>
<p>Ya que <span class="math inline">\(\hat{\sigma}^2\)</span> depende de la suma de cuadrados de residuales, cualquier violación de las hipótesis sobre los errores del modelo, o cualquier especificación equivocada de la forma del modelo, pueden dañar la utilidad de <span class="math inline">\(\hat{\sigma}^2\)</span> como estimador de <span class="math inline">\(\sigma^2\)</span>.</p>
<p>Como <span class="math inline">\(\sigma^2\)</span> se calcula con los residuales del modelo de regresión, se dice que es un <strong>estimador de <span class="math inline">\(\sigma^2\)</span> dependiente del modelo</strong>.</p>
<ul>
<li>Continuando con el ejemplo de soldaduras. Estimemos el <span class="math inline">\(\sigma\)</span>. Haciendolo paso a paso</li>
</ul>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="rls.html#cb12-1" tabindex="-1"></a><span class="co"># 1. Cargar datos</span></span>
<span id="cb12-2"><a href="rls.html#cb12-2" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">&quot;data/data_rls.txt&quot;</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span>
<span id="cb12-3"><a href="rls.html#cb12-3" tabindex="-1"></a>x <span class="ot">&lt;-</span> datos<span class="sc">$</span>Edad</span>
<span id="cb12-4"><a href="rls.html#cb12-4" tabindex="-1"></a>y <span class="ot">&lt;-</span> datos<span class="sc">$</span>Resistencia</span>
<span id="cb12-5"><a href="rls.html#cb12-5" tabindex="-1"></a></span>
<span id="cb12-6"><a href="rls.html#cb12-6" tabindex="-1"></a><span class="co"># 2. Ajustar el modelo de regresión lineal simple</span></span>
<span id="cb12-7"><a href="rls.html#cb12-7" tabindex="-1"></a>modelo <span class="ot">&lt;-</span> <span class="fu">lm</span>(Resistencia <span class="sc">~</span> Edad, <span class="at">data =</span> datos)</span>
<span id="cb12-8"><a href="rls.html#cb12-8" tabindex="-1"></a></span>
<span id="cb12-9"><a href="rls.html#cb12-9" tabindex="-1"></a><span class="co"># 3. Los coeficientes son</span></span>
<span id="cb12-10"><a href="rls.html#cb12-10" tabindex="-1"></a>b0 <span class="ot">&lt;-</span> modelo<span class="sc">$</span>coefficients[<span class="dv">1</span>]</span>
<span id="cb12-11"><a href="rls.html#cb12-11" tabindex="-1"></a>b1 <span class="ot">&lt;-</span> modelo<span class="sc">$</span>coefficients[<span class="dv">2</span>]</span>
<span id="cb12-12"><a href="rls.html#cb12-12" tabindex="-1"></a></span>
<span id="cb12-13"><a href="rls.html#cb12-13" tabindex="-1"></a><span class="co"># 4. Ajustados y residuos</span></span>
<span id="cb12-14"><a href="rls.html#cb12-14" tabindex="-1"></a>yhat <span class="ot">&lt;-</span> b0 <span class="sc">+</span> b1 <span class="sc">*</span> x</span>
<span id="cb12-15"><a href="rls.html#cb12-15" tabindex="-1"></a>e    <span class="ot">&lt;-</span> y <span class="sc">-</span> yhat</span>
<span id="cb12-16"><a href="rls.html#cb12-16" tabindex="-1"></a></span>
<span id="cb12-17"><a href="rls.html#cb12-17" tabindex="-1"></a><span class="co"># 5. SSE por definición</span></span>
<span id="cb12-18"><a href="rls.html#cb12-18" tabindex="-1"></a>SSE <span class="ot">&lt;-</span> <span class="fu">sum</span>(e<span class="sc">^</span><span class="dv">2</span>) </span>
<span id="cb12-19"><a href="rls.html#cb12-19" tabindex="-1"></a></span>
<span id="cb12-20"><a href="rls.html#cb12-20" tabindex="-1"></a><span class="co"># Otra forma de btener los residuos</span></span>
<span id="cb12-21"><a href="rls.html#cb12-21" tabindex="-1"></a>residuos <span class="ot">&lt;-</span> <span class="fu">resid</span>(modelo)</span>
<span id="cb12-22"><a href="rls.html#cb12-22" tabindex="-1"></a>SSE_otro <span class="ot">&lt;-</span> <span class="fu">sum</span>(residuos<span class="sc">^</span><span class="dv">2</span>)</span>
<span id="cb12-23"><a href="rls.html#cb12-23" tabindex="-1"></a></span>
<span id="cb12-24"><a href="rls.html#cb12-24" tabindex="-1"></a><span class="co"># 6. Calcular MSE</span></span>
<span id="cb12-25"><a href="rls.html#cb12-25" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">nrow</span>(datos)              <span class="co"># número de observaciones</span></span>
<span id="cb12-26"><a href="rls.html#cb12-26" tabindex="-1"></a>gl <span class="ot">&lt;-</span> n <span class="sc">-</span> <span class="dv">2</span>                   <span class="co"># grados de libertad</span></span>
<span id="cb12-27"><a href="rls.html#cb12-27" tabindex="-1"></a>MSE <span class="ot">&lt;-</span> SSE <span class="sc">/</span> gl</span>
<span id="cb12-28"><a href="rls.html#cb12-28" tabindex="-1"></a>MSE</span></code></pre></div>
</details>
<pre><code>## [1] 0.3491253</code></pre>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="rls.html#cb14-1" tabindex="-1"></a><span class="co"># 7. Calcular RSE</span></span>
<span id="cb14-2"><a href="rls.html#cb14-2" tabindex="-1"></a>RSE <span class="ot">&lt;-</span> <span class="fu">sqrt</span>(MSE)</span>
<span id="cb14-3"><a href="rls.html#cb14-3" tabindex="-1"></a>RSE</span></code></pre></div>
</details>
<pre><code>## [1] 0.5908683</code></pre>
<p>Cuando ajustamos el modelo con la función <code>modelo &lt;- lm(Resistencia ~ Edad, data = datos)</code> para obtener el RSE de la siguiente forma</p>
<details class=chunk-details open><summary class=chunk-summary><span class=chunk-summary-text>Code</span></summary>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="rls.html#cb16-1" tabindex="-1"></a><span class="do">## estimación de sigma</span></span>
<span id="cb16-2"><a href="rls.html#cb16-2" tabindex="-1"></a><span class="fu">summary</span>(modelo)<span class="sc">$</span>sigma</span></code></pre></div>
</details>
<pre><code>## [1] 0.5908683</code></pre>
<p>A partir de este resultado podemos concluir que <span class="math inline">\(\hat{\sigma}=0.591\)</span>. Por lo tanto, <span class="math inline">\(MSE=0.591^2=0.349\)</span>. Finalmente, el modelo ajustado puede expresarse como</p>
<p><span class="math display">\[\begin{align}
\widehat{\text{Resistencia}}_i &amp;\sim N(\hat{\mu}_i, \hat{\sigma}^2) \\[6pt]
\hat{\mu}_i &amp;= 15.743 - 0.244 \, \text{Edad}_i \\[6pt]
\hat{\sigma}^2 &amp;= 0.591^2 = 0.349
\end{align}\]</span></p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="correglin.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="referencias-1.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/rstudio/bookdown-demo/edit/master/07-rls.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["bookdown-demo.pdf", "bookdown-demo.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
